package com.aero.aplication.main;

import com.aero.aplication.docs.CrearDocumento;
import com.aero.aplication.docs.CrearDocumento1;
import com.aero.aplication.docs.FuecTool;
import com.aero.aplication.dto.CajerosAero;
import com.aero.aplication.dto.Cierre;
import com.aero.aplication.dto.InitHelper;
import com.aero.aplication.dto.JsonDTO;
import com.aero.aplication.dto.RtaDTO;
import com.aero.aplication.dto.Servicios;
import com.aero.aplication.dto.Sitios;
import com.aero.aplication.dto.Ticket;
import static com.aero.aplication.main.InitialContextUtil.getCurrentWorkingDirectory;
import com.aero.aplication.main.TiqueteDialog.ExecuteCargarSrvContable;
import com.aero.aplication.tools.Helper;
import static com.aero.aplication.tools.Helper.getJSONCambiarClave;
import static com.aero.aplication.tools.Helper.getJSONHacerAnulacion;
import static com.aero.aplication.tools.Helper.getJSONHacerCierre;
import static com.aero.aplication.tools.Helper.getJSONReimpresion;
import static com.aero.aplication.tools.Helper.getJSONReimpresionUltimaFactura;
import static com.aero.aplication.tools.Helper.getNumberInt;
import static com.aero.aplication.tools.Helper.getNumberLong;
import static com.aero.aplication.tools.Helper.isOK;
import static com.aero.aplication.tools.Utilidades.validaArray;
import com.aero.rta.conn.WebserviceConnection;
import com.google.gson.Gson;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.OutputStream;
import java.util.Properties;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Hernan
 */
public class Administrar extends javax.swing.JPanel {

    CajerosAero cajeros = new CajerosAero();
    static Sitios sitio = new Sitios();
    String myClave = "";
    Object[] obj = null;
    ButtonGroup bgroup = new ButtonGroup();
    final int ANULACION = 1;
    final int REIMPRESION = 2;
    Boolean isWS;
    String PRINTER = "1";
    String host;
    Integer port;
    Gson gson = new Gson();
    String[] arg;

    /**
     * Creates new form Admin
     */
    public Administrar() {
        initComponents();
     

      
        bgroup.add(jbReimpresion);
        bgroup.add(jbAnular);
        try {
           // String pend = new TiqueteDialog().actualizarContaLocal("ok", sitios.getComprob());
           // btPaiMent.setText("Sincronizar Pagos (" + pend + ")");
        } catch (Exception ex) {
        }

    }

    public CajerosAero leerCajero(CajerosAero ca, String myClave, String host, Integer port, Sitios sitio) {
        this.myClave = myClave;
        this.cajeros = ca;
        JT_CAJERO.setText(cajeros.getNombre());
        this.host = host;
        this.port = port;
        this.sitio = sitio;
        System.out.println("&&&&&&&&&&&&&& stiios amin line 80:   " + sitio.getComprob());
        if (ca.getUsuario().equals("admin")) {
            btPaiMent.setEnabled(true);
        } else {
            btPaiMent.setEnabled(false);
        }
           arg = sitio.getNombre().split("\\|");
        return cajeros;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        REPETIR_CLAVE = new javax.swing.JPasswordField();
        NUEVA_CLAVE = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        CLAVE_ACTUAL = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JT_CAJERO = new javax.swing.JTextField();
        realizarcierre = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jtfAnularFact = new javax.swing.JTextField();
        jbReimpresion = new javax.swing.JRadioButton();
        jbAnular = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btPaiMent = new javax.swing.JButton();

        jLabel6.setText("Contabilizar producido");

        jLabel2.setText("Nueva clave");

        jLabel1.setText("Clave actual");

        jLabel3.setText("Repetir clave");

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Cajero: ");

        JT_CAJERO.setEditable(false);

        realizarcierre.setText("Consultar Cierre");
        realizarcierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarcierreActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfAnularFact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAnularFactKeyTyped(evt);
            }
        });

        jbReimpresion.setText("Reimpresion");

        jbAnular.setText("Anulacion");

        jLabel7.setText("CAMBIAR CLAVE DE ACCESO");

        jLabel8.setText("REIMPRESION/ CANCELACION");

        jLabel9.setText("CIERRE DE CAJA");

        jButton3.setText("Ultima factura");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tx.png"))); // NOI18N

        btPaiMent.setText("Sincronizar Pagos");
        btPaiMent.setEnabled(false);
        btPaiMent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPaiMentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(136, 136, 136))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addGap(83, 83, 83))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(CLAVE_ACTUAL))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel2)
                                                            .addComponent(jLabel3))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(REPETIR_CLAVE)
                                                            .addComponent(NUEVA_CLAVE))))
                                                .addGap(14, 14, 14)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(realizarcierre))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jbReimpresion)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jbAnular))
                                                        .addComponent(jtfAnularFact, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))))
                                .addGap(11, 11, 11))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JT_CAJERO, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPaiMent))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)))
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_CAJERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btPaiMent))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CLAVE_ACTUAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NUEVA_CLAVE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(REPETIR_CLAVE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(realizarcierre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfAnularFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbReimpresion)
                            .addComponent(jbAnular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    String clave_actual = CLAVE_ACTUAL.getText();
    String nueva_clave = NUEVA_CLAVE.getText();
    String repetir_clave = REPETIR_CLAVE.getText();

    if (!myClave.equals(clave_actual)) {
        JOptionPane.showMessageDialog(null, "CLAVE ACTUAL NO ES CORRECTA");
    } else {
        if (!nueva_clave.equals(repetir_clave)) {
            JOptionPane.showMessageDialog(null, "LAS DOS CLAVES DEBE SER IGUALES");
            REPETIR_CLAVE.setText("");
            REPETIR_CLAVE.setBackground(Color.green);
        } else {
            try {
                cajeros.setClave(nueva_clave);
                String nvClave = cajeros.getClave();
                String usuario = cajeros.getUsuario();
                String jsonLugares = new WebserviceConnection(host, port).getStatusAccount(getJSONCambiarClave(usuario, nvClave, cajeros.getIdUsuario()));
                String error = "No fue posible actualizar los datos del usuario";
                if (isOK(jsonLugares)) {
                    RtaDTO obj = gson.fromJson(jsonLugares, RtaDTO.class);

                    for (JsonDTO p : obj.getAlertas()) {
                        if (p.getError().equals("ok")) {
                            error = "Actualizado correctamente !";
                        }
                    }
                }
                CLAVE_ACTUAL.setText("");
                NUEVA_CLAVE.setText("");
                REPETIR_CLAVE.setText("");

                JOptionPane.showMessageDialog(null, error);
                // this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR");
            }
        }
    }
}//GEN-LAST:event_jButton2ActionPerformed

    private void realizarcierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarcierreActionPerformed
        // TODO add your handling code here:
        mostrarCierre("no");
    }//GEN-LAST:event_realizarcierreActionPerformed

    public boolean mostrarCierre(String salir) {

        Properties pr = new Properties();

        try {
            pr.load(new FileReader(new InitHelper().getCurrentWorkingDirectory() + "/factura.properties"));
        } catch (Exception e) {
            e.printStackTrace();
        }

        String jsonCierre = new WebserviceConnection(host, port).getStatusAccount(getJSONHacerCierre(cajeros.getIdUsuario(),cajeros.getIdSitio(), false));

        String error = "Cierre no encontrado, favor intente nuevamente";
        Cierre cie = new Cierre();
        String OK = "no";
        boolean isOk = true;
        if (isOK(jsonCierre)) {
            RtaDTO obj = gson.fromJson(jsonCierre, RtaDTO.class);
            for (JsonDTO p : obj.getAlertas()) {
                if (p.getError().equals("ok")) {
                    error = "Cierre pendiente!";
                    cie = configurarCierre(p);
                    OK = p.getError();
                } else {
                    error = p.getError();
                }
            }

            error += "Cantidad: " + cie.getCantidad();
            error += "\nInicio : " + cie.getInicio();
            error += "\nFinal: " + cie.getFin();
            error += "\n -------------------";
            error += "\nValor Efectivo: " + cie.getValorE();
            error += "\nValor Debito: " + cie.getValorD();
            error += "\nValor Credito: " + cie.getValorC();
            error += "\nAnulaciones: " + cie.getCantidadAnuladas();
            error += "\n=====================";
            error += "\nValor Anualdas: " + cie.getValorAnualdos();
            error += "\nValor Total: $ " + cie.getValorTotal();
            error += "\nCajero: " + cie.getUsuarioNombre();
        }
        int response = 1;
        if (!OK.equals("no")) {
            isOk = false;
            response = JOptionPane.showConfirmDialog(null, "\nDesea Realizar cierre?\n\n " + error, "Confirmar cierre", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        } else {
            if (salir != null && salir.equals("si")) {

            } else {
                JOptionPane.showMessageDialog(null, "Cierre no encontrado, favor intente nuevamente");
            }

        }

        error = "No fue posible realizar el cierre, favor intentelo nuevamente";
        if (response == JOptionPane.NO_OPTION) {
        } else if (response == JOptionPane.YES_OPTION) {
            try {
                pr.load(new FileReader(getCurrentWorkingDirectory() + "/configurar.properties"));
                jsonCierre = new WebserviceConnection(host, port).getStatusAccount(getJSONHacerCierre(cajeros.getIdUsuario(),cajeros.getIdSitio(), true));
                if (isOK(jsonCierre)) {
                    RtaDTO obj = gson.fromJson(jsonCierre, RtaDTO.class);
                    for (JsonDTO p : obj.getAlertas()) {
                        error = p.getError();
                    }
                    if (error.equals("ok")) {
                        error = "Cierre realizado con exito! enviar reporte impreso...";
                        isOk = true;

                        byte[] bytes = new CrearDocumento().generarCierreFactura(cie, pr);
                        if (bytes != null) {
                            imprimirCierre(bytes);
                        }

                        // new TiqueteDialog().new ExecuteCargarSrvContable(sitio.getComprob()).execute();
                    } else {
                        error = "No fue posible realizar el cierre, favor intentelo nuevamente";
                        JOptionPane.showMessageDialog(null, error);
                        isOk = false;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, error);
                }
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, error);
            }
        }
        return isOk;
    }

    public Cierre configurarCierre(JsonDTO p) {
        Cierre cie = new Cierre();
        cie.setCantidad(getNumberInt(p.getCantidad()));
        cie.setInicio(getNumberInt(p.getInicio()));
        cie.setFin(getNumberInt(p.getFin()));
        cie.setValorE(getNumberInt(p.getValorE()));
        cie.setValorD(getNumberInt(p.getValorD()));
        cie.setValorC(getNumberInt(p.getValorC()));
        cie.setValorTotal(getNumberInt(p.getValorTotal()));
        cie.setUsuarioNombre(p.getUsuarioNombre());
        cie.setValorAnualdos(getNumberInt(p.getValorAnulados()));
        cie.setCantidadAnuladas(getNumberInt(p.getCantidadAnulads()));
        cie.setFecha(Helper.toDateYYMMDDHHMM(p.getFecha()));
        cie.setSitioNombre(p.getSitioNombre());
        return cie;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Integer decorate = jbAnular.isSelected() ? 1 : jbReimpresion.isSelected() ? 2 : 0;

        if (jtfAnularFact.getText() != null && jtfAnularFact.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese numero de factura");
            jtfAnularFact.setBackground(Color.YELLOW);

        } else {
            String direccionDestino = "";
            Long numFactura = new Long(jtfAnularFact.getText());
            Servicios retA = null;
            Ticket tiquete = new Ticket();

            String msj = "";
            try {
                if (decorate.equals(ANULACION)) {

                    String PORQUE = "";
                    if (PORQUE == "") {
                        while (!(PORQUE != "")) {
                            PORQUE = JOptionPane.showInputDialog(this, "Motivo de Anulacion", "Ingresar motivo", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }

                    String jsonAnulacion = new WebserviceConnection(host, port).getStatusAccount(getJSONHacerAnulacion(numFactura, PORQUE, sitio.getIdSitio(), arg[0]));
                    String error = "No fue posible anular la factura, favor intentelo nuevamente";
                    
                     if (isOK(jsonAnulacion)) {
                 RtaDTO obj = gson.fromJson(jsonAnulacion, RtaDTO.class);
                 tiquete = obj.getAlertas().get(0).getTiquete();
                    
         
                        
                        
                       // System.out.println("tiquete:   " + tiquete);
                        //  System.out.println("tiquete:   " + tiquete.getComprob()+"   estado"+obj.getEstado());
                       /* for (JsonDTO p : obj.getAlertas()) {
                            direccionDestino = p.getDireccion();
                            System.out.println("fehca:   " + p.getFecha());
                            if (p.getError().equals("ok")) {
                                error = "Factura anulada correctamente!";
                                tiquete = cargarTKReimpNuevo(tiquete, msj, p);
                                tiquete.setId(getNumberLong(p.getId()));

                            }

                        }*/
                    } else {
                        msj = "no";
                    }
                    retA = new Servicios();

                    JOptionPane.showMessageDialog(null, error);
                    msj = "ANULACION";
                } else if (decorate.equals(REIMPRESION)) {
                    msj = "REIMPRESION";

                    String jsonReimpresion = new WebserviceConnection(host, port).getStatusAccount(getJSONReimpresion(numFactura, sitio.getIdSitio(), arg[0]));
                    //Ticket factura = null;
                    try {
                       tiquete = gson.fromJson(jsonReimpresion, Ticket.class);
                       //tiquete = obj.getAlertas().get(0).getTiquete();
                        System.out.println("errrrrr____"+tiquete.getError());
                        //factura = gson.fromJson(jsonReimpresion, Ticket.class);
                        if (tiquete.getError().equals("ok")) {
                            genereFUEC2(tiquete);//generar PDF

                           // if (sitio.getIdSitio().equals("8")) {
                                generePOST(tiquete, sitio);//iresion impresora POST
                            //}
                        } else {
                            JOptionPane.showMessageDialog(null, "Factura no disponible para reimpresion");
                        }
                    } catch (RuntimeException e) {
                        e.printStackTrace();
                    }
                    String error = "No se encontro la factura, favor intente nuevamente";

                } else {
                    JOptionPane.showMessageDialog(null, "Es necesario seleccionar una opcion");

                }
//if (msj != "no") {
                if (false) {
                    byte[] bytes = null;
                    byte[] bytes2 = null;

                    int rta = JOptionPane.showConfirmDialog(null, "\nDesea imprimir Factua?", msj, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                    if (rta == JOptionPane.YES_OPTION) {
                        try {
                            System.out.println("values.... 557 ");
                            Properties pr = new Properties();
                            pr.load(new FileReader(new InitHelper().getCurrentWorkingDirectory() + "/factura.properties"));

                            bytes = new CrearDocumento().generarFactura(tiquete, sitio, pr, "Reimpresion");

                            isWS = new Boolean(pr.getProperty("WS"));
                            pr.load(new FileReader(getCurrentWorkingDirectory() + "/configurar.properties"));
                            PrintPdf printPDFFile = new PrintPdf(bytes, "Test Print PDF");
                            printPDFFile.print();

                            bytes2 = new CrearDocumento1().generarFactura(tiquete, sitio, pr, "reimpreso", sitio);
                            String path = new InitHelper().getCurrentWorkingDirectory() + "/fac_nuevo.pdf";
                            Desktop.getDesktop().open(new File(path));

                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, " Reintentar impresion...");
                        }
                    }
                } else {
                    // JOptionPane.showMessageDialog(null, "NO EXISTEN REGISTROS, INTENTE NUEVAMENTE");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "No fue posible procesar su solicitud!!!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void generePOST(Ticket tiquete, Sitios sitios) {
        try {
            Properties pr = new Properties();
            pr.load(new FileReader(new InitHelper().getCurrentWorkingDirectory() + "/factura.properties"));

            isWS = new Boolean(pr.getProperty("WS"));
            pr.load(new FileReader(getCurrentWorkingDirectory() + "/configurar.properties"));
            String[] CP = new String[]{"===COPIA EMPRESA===", "===COPIA CONDUCTOR===", "===COPIA USUARIO==="};
            for (int i = 0; i < 3; i++) {
                byte[] bytes = new CrearDocumento().generarFactura(tiquete, sitios, pr, CP[i]);
                PrintPdf printPDFFile = new PrintPdf(bytes, "Test Print PDF");
                printPDFFile.print();
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al imprimir el archivo, favor reimprimirlo nuevamente");
        }
    }

    public void genereFUEC2(Ticket tiket) {
        try {
            Properties pr = new Properties();
            pr.load(new FileReader(new InitHelper().getCurrentWorkingDirectory() + "/factura.properties"));
            isWS = new Boolean(pr.getProperty("WS"));
            pr.load(new FileReader(getCurrentWorkingDirectory() + "/configurar.properties"));

            String path = new InitHelper().getCurrentWorkingDirectory() + "/" + tiket.getConsecutivo() + "_fac_nuevo.pdf";
            byte[] bytes2 = new FuecTool().crearFuec(tiket, path);

            Desktop.getDesktop().open(new File(path));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al imprimir el archivo, favor reimprimirlo nuevamente");
        }
    }

    public Ticket cargarTK_old(Ticket tiquete, String msj, JsonDTO p) throws Exception {
        String[] _nits = new LoadPlaca().cargarNits2(p.getPlaca());

        tiquete.setId(getNumberLong(p.getId()));
        tiquete.setValor(p.getValor());
        tiquete.setPlaca(p.getPlaca());
        tiquete.set2300(p.getValor());
        tiquete.setDistancia(getNumberInt("0"));
        tiquete.setFecha(Helper.getColCurrentTime());
        CajerosAero cajeroAux = new CajerosAero();
        cajeroAux.setNombre(p.getNombreCajero());
        tiquete.setUsuario(cajeroAux);
        tiquete.setMarca(_nits[2]);
        tiquete.setModelo(_nits[3]);
        tiquete.setLogEmpreVehiculo(_nits[4]);
        tiquete.setLogFirmaVehiculo(_nits[5]);
        tiquete.setAutorizado(_nits[6]);
        tiquete.setTipoPago(msj);
        tiquete.setUrlLogo(_nits[4]);

        String dir_nom_nit[] = p.getDireccion().split("\\|");
        tiquete.setDestino(dir_nom_nit[0]);
        if (dir_nom_nit.length > 1) {

            tiquete.setNombre(dir_nom_nit[1]);
        } else {
            tiquete.setNombre("");
        }
        if (dir_nom_nit.length > 2) {
            tiquete.setNit(dir_nom_nit[2]);
        } else {
            tiquete.setNit("");
        }

        tiquete.setNitConductor(validaArray(_nits, 9));
        tiquete.setMarca(validaArray(_nits, 4));
        tiquete.setModelo(validaArray(_nits, 3));
        tiquete.setLogEmpreVehiculo(validaArray(_nits, 0));
        tiquete.setLogFirmaVehiculo(validaArray(_nits, 8));
        tiquete.setAutorizado(validaArray(_nits, 0));
        tiquete.setTipoPago("005");
        String nombreConductor = validaArray(_nits, 8);
        tiquete.setNombreConductor1(nombreConductor);
        tiquete.setApellidoConductor1("");
        tiquete.setCcConductor1(validaArray(_nits, 9));
        tiquete.setLicenciaConductor1(validaArray(_nits, 10));
        tiquete.setVigenciaConductor1(validaArray(_nits, 11));
        tiquete.setNombreConductor2(validaArray(_nits, 12));
        tiquete.setApellidoConductor2("");
        tiquete.setCcConductor2(validaArray(_nits, 13));
        tiquete.setLicenciaConductor2(validaArray(_nits, 14));
        tiquete.setVigenciaConductor2(validaArray(_nits, 15));
        tiquete.setNombreResponsable(validaArray(_nits, 16));
        tiquete.setApellidoResponsable("");
        tiquete.setCcResponsable(validaArray(_nits, 17));
        tiquete.setTelResponsable(validaArray(_nits, 18));
        tiquete.setDireccionResponsable(validaArray(_nits, 19));
        tiquete.setEmpresa(validaArray(_nits, 0));
        tiquete.setClase(validaArray(_nits, 5));
        tiquete.setNumeroInterno(validaArray(_nits, 6));
        tiquete.setNumeroTarjetaOpe(validaArray(_nits, 7));
        tiquete.setNit(validaArray(_nits, 17));

        return tiquete;

    }

    public Ticket cargarTKReimp(Ticket tiquete, String msj, JsonDTO p) throws Exception {
        String[] _nits = new LoadPlaca().cargarNits2(tiquete.getPlaca());
        
          tiquete.setMarca(_nits[2]);
        tiquete.setModelo(_nits[3]);
        tiquete.setLogEmpreVehiculo(_nits[4]);
        tiquete.setLogFirmaVehiculo(_nits[5]);
        tiquete.setAutorizado(_nits[6]); 
         String dir_nom_nit[] = p.getDireccion().split("\\|");
        tiquete.setDestino(dir_nom_nit[0]);

        tiquete.setId(getNumberLong(p.getId()));
        tiquete.setValor(p.getValor());
        tiquete.setPlaca(p.getPlaca());
        tiquete.set2300(p.getValor());
        tiquete.setDistancia(getNumberInt("0"));
        CajerosAero cajeroAux = new CajerosAero();
        cajeroAux.setNombre(p.getNombreCajero());
        tiquete.setUsuario(cajeroAux);
      
        tiquete.setTipoPago(msj);
        tiquete.setUrlLogo(_nits[4]);
        tiquete.setFecha(Helper.getColCurrentTime());
        tiquete.setFechaFin(Helper.toDateYYMMDDHHMM(Helper.addDay()));

       // String dir_nom_nit[] = p.getDireccion().split("\\|");
       
        if (dir_nom_nit.length > 1) {

            tiquete.setNombre(dir_nom_nit[1]);
        } else {
            tiquete.setNombre("");
        }
        if (dir_nom_nit.length > 2) {
            tiquete.setNit(dir_nom_nit[2]);
        } else {
            tiquete.setNit("");
        }

        tiquete.setNitConductor(validaArray(_nits, 9));
        tiquete.setMarca(validaArray(_nits, 4));
        tiquete.setModelo(validaArray(_nits, 3));
        tiquete.setLogEmpreVehiculo(validaArray(_nits, 0));
        tiquete.setLogFirmaVehiculo(validaArray(_nits, 8));
        tiquete.setAutorizado(validaArray(_nits, 0));
        tiquete.setTipoPago("005");
        String nombreConductor = validaArray(_nits, 8);
        tiquete.setNombreConductor1(nombreConductor);
        tiquete.setApellidoConductor1("");
        tiquete.setCcConductor1(validaArray(_nits, 9));
        tiquete.setLicenciaConductor1(validaArray(_nits, 10));
        tiquete.setVigenciaConductor1(validaArray(_nits, 11));
        tiquete.setNombreConductor2(validaArray(_nits, 12));
        tiquete.setApellidoConductor2("");
        tiquete.setCcConductor2(validaArray(_nits, 13));
        tiquete.setLicenciaConductor2(validaArray(_nits, 14));
        tiquete.setVigenciaConductor2(validaArray(_nits, 15));
        tiquete.setNombreResponsable(validaArray(_nits, 16));
        tiquete.setApellidoResponsable("");
        tiquete.setCcResponsable(validaArray(_nits, 17));
        tiquete.setTelResponsable(validaArray(_nits, 18));
        tiquete.setDireccionResponsable(validaArray(_nits, 19));
        tiquete.setEmpresa(validaArray(_nits, 0));
        tiquete.setClase(validaArray(_nits, 5));
        tiquete.setNumeroInterno(validaArray(_nits, 6));
        tiquete.setNumeroTarjetaOpe(validaArray(_nits, 7));
        tiquete.setNit(validaArray(_nits, 17));

        return tiquete;

    }

    public Ticket cargarTKReimpNuevo(Ticket tiquete, String msj, JsonDTO p) throws Exception {
        String[] _nits = new LoadPlaca().cargarNits2(p.getPlaca());

        tiquete.setId(getNumberLong(p.getId()));
        tiquete.setValor(p.getValor());
        tiquete.setPlaca(p.getPlaca());
        tiquete.set2300(p.getValor());
        tiquete.setDistancia(getNumberInt("0"));
        CajerosAero cajeroAux = new CajerosAero();
        cajeroAux.setNombre(p.getNombreCajero());
        tiquete.setUsuario(cajeroAux);
        tiquete.setMarca(_nits[2]);
        tiquete.setModelo(_nits[3]);
        tiquete.setLogEmpreVehiculo(_nits[4]);
        tiquete.setLogFirmaVehiculo(_nits[5]);
        tiquete.setAutorizado(_nits[6]);
        tiquete.setTipoPago(msj);
        tiquete.setUrlLogo(_nits[4]);
        tiquete.setFecha(Helper.getColCurrentTime());
        tiquete.setFechaFin(Helper.toDateYYMMDDHHMM(Helper.addDay()));

        String dir_nom_nit[] = p.getDireccion().split("\\|");
        tiquete.setDestino(dir_nom_nit[0]);
        if (dir_nom_nit.length > 1) {

            tiquete.setNombre(dir_nom_nit[1]);
        } else {
            tiquete.setNombre("");
        }
        if (dir_nom_nit.length > 2) {
            tiquete.setNit(dir_nom_nit[2]);
        } else {
            tiquete.setNit("");
        }

        tiquete.setNitConductor(validaArray(_nits, 9));
        tiquete.setMarca(validaArray(_nits, 4));
        tiquete.setModelo(validaArray(_nits, 3));
        tiquete.setLogEmpreVehiculo(validaArray(_nits, 0));
        tiquete.setLogFirmaVehiculo(validaArray(_nits, 8));
        tiquete.setAutorizado(validaArray(_nits, 0));
        tiquete.setTipoPago("005");
        String nombreConductor = validaArray(_nits, 8);
        tiquete.setNombreConductor1(nombreConductor);
        tiquete.setApellidoConductor1("");
        tiquete.setCcConductor1(validaArray(_nits, 9));
        tiquete.setLicenciaConductor1(validaArray(_nits, 10));
        tiquete.setVigenciaConductor1(validaArray(_nits, 11));
        tiquete.setNombreConductor2(validaArray(_nits, 12));
        tiquete.setApellidoConductor2("");
        tiquete.setCcConductor2(validaArray(_nits, 13));
        tiquete.setLicenciaConductor2(validaArray(_nits, 14));
        tiquete.setVigenciaConductor2(validaArray(_nits, 15));
        tiquete.setNombreResponsable(validaArray(_nits, 16));
        tiquete.setApellidoResponsable("");
        tiquete.setCcResponsable(validaArray(_nits, 17));
        tiquete.setTelResponsable(validaArray(_nits, 18));
        tiquete.setDireccionResponsable(validaArray(_nits, 19));
        tiquete.setEmpresa(validaArray(_nits, 0));
        tiquete.setClase(validaArray(_nits, 5));
        tiquete.setNumeroInterno(validaArray(_nits, 6));
        tiquete.setNumeroTarjetaOpe(validaArray(_nits, 7));
        tiquete.setNit(validaArray(_nits, 17));

        return tiquete;

    }
    private void jtfAnularFactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAnularFactKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfAnularFactKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Ticket tiquete = new Ticket();
        try {
            byte[] bytes = null;
            String jsonReimpresionUltFact = new WebserviceConnection(host, port).getStatusAccount(getJSONReimpresionUltimaFactura(getNumberInt(cajeros.getIdUsuario()), arg[0]));

            String error = "No hay facturas del usuario";
          //  System.out.println("rta___"+jsonReimpresionUltFact);
            if (isOK(jsonReimpresionUltFact)) {
                 RtaDTO obj = gson.fromJson(jsonReimpresionUltFact, RtaDTO.class);
                 tiquete = obj.getAlertas().get(0).getTiquete();
                /*for (JsonDTO p : obj.getAlertas()) {
                    tiquete.setDestino(p.getDireccion());
                    if (p.getError().equals("ok")) {
                        error = "REIMPRESION";
                        System.out.println("..................reimpresion de factura"+);
                        tiquete = cargarTKReimp(tiquete, "005", p);
                    }

                }*/
                System.out.println("...tiquete....."+tiquete);
                System.out.println("tiquete....."+tiquete.getPlaca()+"    "+tiquete.getValor());
            } else {
                error = "no";
            }

//            String dir_nom_nit[] = retA.getAddres().split("\\|");
            if (error != "no") {
//                byte[] bytes = null;
//                tiquete.setDestino(dir_nom_nit[0]);
//                if (dir_nom_nit.length > 1) {
//                    tiquete.setNombre(dir_nom_nit[1]);
//                }
//                if (dir_nom_nit.length > 2) {
//                    tiquete.setNit(dir_nom_nit[2]);
//                }
//
//                tiquete.setId(new Long(retA.getNumero()));
//                tiquete.setValor(retA.getValor().toString());
//                tiquete.setPlaca(retA.getAutoPlaca());
//                tiquete.set2300(retA.getValor().toString());
//                tiquete.setDistancia(new Integer("0"));
//                tiquete.setFecha((new Helper().getColCurrentTime()));
//
//                tiquete.setUsuario(retA.getUsuarios());
//                tiquete.setTipoPago("ANULADO");

                try {
                    Properties pr = new Properties();
                    pr.load(new FileReader(new InitHelper().getCurrentWorkingDirectory() + "/factura.properties"));

                    bytes = new CrearDocumento1().generarFactura(tiquete, sitio, pr, "Reimpresion", sitio);
                    isWS = new Boolean(pr.getProperty("WS"));
                    pr.load(new FileReader(getCurrentWorkingDirectory() + "/configurar.properties"));

                    if (isWS == false) {
                        String URL = tiquete.getId().toString();
                        OutputStream rutaArchivo = new FileOutputStream("c:/R_" + URL);
                        rutaArchivo.write(bytes);
                    } else {
                        System.out.println("No Creando factura.....");
                    }
                    PrintPdf printPDFFile = new PrintPdf(bytes, "Test Print PDF");
                    printPDFFile.print();
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, " Reintentar impresion...");
                    try {
                        Properties pr = new Properties();
                        pr.load(new FileReader(new InitHelper().getCurrentWorkingDirectory() + "/factura.properties"));
                        bytes = new CrearDocumento1().generarFactura(tiquete, sitio, pr, "Reimpresion", sitio);
                        PrintPdf printPDFFile = new PrintPdf(bytes, "Test Print PDF");
                        printPDFFile.print();
                    } catch (Exception ee) {
                        JOptionPane.showMessageDialog(null, "Servico creado, pero tenemos un inconveniente al imprimirlo,\nRevisar cola de impresion\nposiblemente la impresora no este disponible");
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btPaiMentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPaiMentActionPerformed
        // TODO add your handling code here:

//        int rta = JOptionPane.showConfirmDialog(null, "Confirmar solicitud, esta seguro?", "Cargar datos de nuevo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//        System.out.println("host: " + host + ": ort " + port);
//        if (rta == JOptionPane.YES_OPTION) {
//            String jsonGeo = new WebserviceConnection(host, port).getStatusAccount(getLoadPaiMent());
//
//            long precio = 0;
//
//            JsonDTO retA = new JsonDTO();
//            if (isOK(jsonGeo)) {
//                RtaDTO obj = gson.fromJson(jsonGeo, RtaDTO.class);
//                JOptionPane.showMessageDialog(null, "Se cargaron un total de " + obj.getAlertas().iterator().next().getCantidad() + " registros");
//            }
//        }
        System.out.println("comprobante adminstrar 825:   " + sitio.getComprob());
        new TiqueteDialog().new ExecuteCargarSrvContable(sitio.getComprob()).execute();

        try {
            //Thread.sleep(3000);
            //String pend = new TiqueteDialog().actualizarContaLocal("ok");
            //btPaiMent.setText("Sincronizar Pagos (" + pend + ")");
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btPaiMentActionPerformed
    public void imprimirCierre(byte[] bytes) {
        try {
            PrintPdf printPDFFile = new PrintPdf(bytes, "Test Print PDF");
            printPDFFile.print();
        } catch (Exception e) {
            Cierre cierre = (Cierre) obj[1];
            String msj = "Cierre realizado con exito, error al imprimir revsiar impresora.";
            msj += "\nTotal: " + cierre.getValorTotal();
            msj += "\nCajero: " + cierre.getUsuarioNombre();
            JOptionPane.showMessageDialog(null, msj);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CLAVE_ACTUAL;
    private javax.swing.JTextField JT_CAJERO;
    private javax.swing.JPasswordField NUEVA_CLAVE;
    private javax.swing.JPasswordField REPETIR_CLAVE;
    private javax.swing.JButton btPaiMent;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton jbAnular;
    private javax.swing.JRadioButton jbReimpresion;
    private javax.swing.JTextField jtfAnularFact;
    private javax.swing.JButton realizarcierre;
    // End of variables declaration//GEN-END:variables
}
