/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aero.aplication.main;

import com.aero.aplication.dto.CajerosAero;
import com.aero.aplication.dto.JsonDTO;
import com.aero.aplication.dto.RtaDTO;
import com.aero.aplication.dto.Sitios;
import java.io.FileInputStream;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import static com.aero.aplication.main.UtilContest.getCurrentWorkingDirectory;
import com.aero.rta.conn.WebserviceConnection;
import static com.aero.aplication.tools.Helper.getNumberInt;
import static com.aero.aplication.tools.Helper.getJSONSelectLogin;
import static com.aero.aplication.tools.Helper.getJSONLogin;
import static com.aero.aplication.tools.Helper.isOK;
import com.google.gson.Gson;
import java.awt.Button;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ButtonGroup;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Hernan Sanchez
 */
public class Principal extends javax.swing.JFrame {

    private static final Logger log = Logger.getLogger(Principal.class);
    static Principal frame = new Principal();
    static List<Sitios> sitios;
    static Integer idSitio;
    String jsonIn;
    static String hostAddress;
    static String port;
    static String hostAddress_rta;
    static String port_rta;
    ButtonGroup bgroup = new ButtonGroup();

    Gson gson = new Gson();
    static CajerosAero cajero = new CajerosAero();

    /**
     * Creates new form Principal
     */
    public Principal() {

        try {

            Properties configFile = readProperties();
            int i = 1;

            hostAddress = configFile.getProperty("HOST");
            port = configFile.getProperty("PORT");
            hostAddress_rta = configFile.getProperty("HOST_RTA");
            port_rta = configFile.getProperty("PORT_RTA");

            jsonIn = new WebserviceConnection(hostAddress, getNumberInt(port)).getStatusAccount(getJSONSelectLogin());

            initComponents();
            if (jsonIn != null && !jsonIn.isEmpty()) {
                System.out.println("ok 1 " + jsonIn);
                RtaDTO obj = new Gson().fromJson(jsonIn, RtaDTO.class);
                System.out.println("ok2 "+obj.getError());
                for (JsonDTO p : obj.getAlertas()) {
                    
                    jcbSitios.addItem(p.getNombreSitio());
                    
                  
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public Properties readProperties() throws Exception {
        String userDir = getCurrentWorkingDirectory();
        String hostFile = userDir + "host.properties";
        Properties configFile = new Properties();
        configFile.load(new FileInputStream(hostFile));
        return configFile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbSitios = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        clave = new javax.swing.JPasswordField();
        usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tx.png"))); // NOI18N

        jcbSitios.setModel(new javax.swing.DefaultComboBoxModel());

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                claveKeyTyped(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clave.png"))); // NOI18N
        jLabel3.setText("Clave:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        jLabel2.setText("Usuario:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setText("V 6.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbSitios, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usuario)
                                .addComponent(clave)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jcbSitios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void login() {
        Sitios mySitio = null;
        try {

            System.out.println("1");
            // TODO add your handling code here:
            String _usuario = usuario.getText();
            String _clave = clave.getText();

            String _pp = jcbSitios.getSelectedItem().toString();

            if (isOK(jsonIn)) {
                RtaDTO obj = gson.fromJson(jsonIn, RtaDTO.class);
                for (JsonDTO p : obj.getAlertas()) {
                    if (p.getNombreSitio().equals(_pp)) {
                        idSitio = getNumberInt(p.getIdSitio());
                        mySitio = new Sitios();
                        mySitio.setNombre(p.getNombreSitio());
                        mySitio.setDireccion(p.getDireccion());
                        mySitio.setIdSitio(p.getIdSitio());
                        mySitio.setComprob(p.getComprob().split("\\|")[0]);
                        mySitio.setFuec(p.getFuec());
                    }

                }
            }

            
            
            
            String jsonLogin = new WebserviceConnection(hostAddress, getNumberInt(port)).getStatusAccount(getJSONLogin(_usuario, _clave, idSitio.toString(), mySitio.getComprob()));

            System.out.println("values: " + jsonLogin);
            if (isOK(jsonLogin)) {
                System.out.println("+values: " + jsonLogin);
                RtaDTO obj = gson.fromJson(jsonLogin, RtaDTO.class);
                System.out.println("obj.getError()   " + obj.getError());
                if (obj.getError() != null && obj.getError().equals("ok")) {
                    for (JsonDTO p : obj.getAlertas()) {

                        cajero.setUsuario(p.getUsuario());
                        cajero.setNombre(p.getNombre());
                        cajero.setClave(p.getClave());
                        cajero.setIdUsuario(p.getId());
                        cajero.setIdSitio(p.getIdSitio());

                        AplicationAero page = new AplicationAero(hostAddress, getNumberInt(port), mySitio);
                        page.setExtendedState(page.MAXIMIZED_BOTH);
                        page.leerUsuario(cajero, _clave, mySitio, hostAddress, getNumberInt(port), readProperties());
                        page.setVisible(true);
                        page.setLocationRelativeTo(null);
                        page.setSize(900, 400);
                        this.setVisible(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Datos incorrectos y/o No hay conexion con el servidor", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Datos incorrectos y/o No hay conexion con el servidor", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        JDialog jd = new JDialog(this, "Ayuda", true);
        jd.getContentPane();
        jd.add(new Ayuda());
        jd.setSize(350, 200);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void claveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_claveKeyTyped
        // TODO add your handling code here:
//        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
//            Toolkit.getDefaultToolkit().beep();
//            evt.consume();
//        }
        String enter = "enter";
        int condition = JComponent.WHEN_FOCUSED;
        InputMap iMap = clave.getInputMap(condition);
        ActionMap aMap = clave.getActionMap();

        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), enter);
        aMap.put(enter, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                login();
            }
        });
    }//GEN-LAST:event_claveKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField clave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox jcbSitios;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
