/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aero.aplication.main;

import com.aero.aplication.docs.CrearDocumento;
import com.aero.aplication.docs.CrearDocumento1;
import com.aero.aplication.docs.FuecTool;
import com.aero.aplication.dto.CajerosAero;
import com.aero.aplication.dto.InitHelper;
import com.aero.aplication.dto.JsonDTO;
import com.aero.aplication.dto.Persona;
import com.aero.aplication.dto.RtaDTO;
import com.aero.aplication.dto.Servicios;
import com.aero.aplication.dto.Sitios;
import com.aero.aplication.dto.Ticket;
import java.io.FileReader;
import java.text.DecimalFormat;
import java.util.Properties;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import static com.aero.aplication.main.InitialContextUtil.getCurrentWorkingDirectory;
import com.aero.aplication.tools.Helper;
import static com.aero.aplication.tools.Helper.fechaActual;
import static com.aero.aplication.tools.Helper.getNumeroLargo;
import static com.aero.aplication.tools.Helper.getString;
import com.aero.aplication.tools.MensajeTmp;
import java.awt.print.PrinterJob;

import com.aero.rta.conn.WebserviceConnection;

import com.google.gson.Gson;

import static com.aero.aplication.tools.Utilidades.validaArray;
import com.aero.aplication.tools.isProduccion;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.RootPaneContainer;
import javax.swing.SwingWorker;

/**
 *
 * @author hsancheza
 */
public class TiqueteDialog extends JDialog {

    CajerosAero cajeros = new CajerosAero();
    Sitios sitios = new Sitios();
    Boolean isWS = new Boolean("false");
    Servicios srv = new Servicios();
    Ticket tiquete = new Ticket();
    private static final Logger log = Logger.getLogger(AplicationAero.class);
    DecimalFormat formateador = new DecimalFormat("###,###.##");
    boolean hayPlacas;
    String PLACA = "";
    String PRINTER = "1";
    static String host;
    static Integer port;
    Gson gson = new Gson();
    String comprob;
    Properties properties;
    String base;

    String arg[];
    boolean validarPlaca = true;

    public TiqueteDialog(java.awt.Frame parent, boolean modal) {

        super(parent, modal);

        try {
            // printerServicesRemote = (PrinterServicesDelegateRemote) new UtilContest().jndi(printerServicesRemote, "PrinterServicesDelegate", "remote");
            initComponents();

            PrinterJob pjob = PrinterJob.getPrinterJob();
            if (pjob != null) {
                if (pjob.getPrintService() != null && pjob.getPrintService().getName().contains("Receipt")) {
                    PRINTER = "1";
                } else {
                    PRINTER = "2";
                }
                System.out.println("PRINTER:" + PRINTER);
                jButton3.setEnabled(false);
            } else {
                System.out.println("Favor instale la impresora como predeterminada...");
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("hay un errort...");
        }
    }

    public TiqueteDialog() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        msjError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ckPin = new javax.swing.JCheckBox();
        pinPago = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        chkRetiro = new javax.swing.JCheckBox();
        retiro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfMainAccount = new javax.swing.JTextField();
        saldo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totalRetiros = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        msError = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jtfDarVueltas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfCredito = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfEfectivo = new javax.swing.JTextField();
        jtfDebito = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDireccion = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jtfDolarHoy = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfCantidadDolar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfDolarPesos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        userInformation = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));

        ckPin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckPin.setForeground(new java.awt.Color(0, 204, 51));
        ckPin.setText("ModiPay");
        ckPin.setEnabled(false);
        ckPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPinActionPerformed(evt);
            }
        });

        pinPago.setEditable(false);
        pinPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinPagoActionPerformed(evt);
            }
        });
        pinPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pinPagoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinPagoKeyTyped(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 0));
        jButton3.setText("Cargar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        chkRetiro.setBackground(new java.awt.Color(255, 204, 204));
        chkRetiro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkRetiro.setText("Retirar");
        chkRetiro.setEnabled(false);
        chkRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRetiroActionPerformed(evt);
            }
        });

        retiro.setEditable(false);
        retiro.setBackground(new java.awt.Color(204, 255, 204));
        retiro.setEnabled(false);
        retiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiroActionPerformed(evt);
            }
        });
        retiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                retiroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                retiroKeyTyped(evt);
            }
        });

        jLabel12.setText("Cuenta principal");

        jtfMainAccount.setEditable(false);
        jtfMainAccount.setBackground(new java.awt.Color(204, 255, 153));

        saldo.setEditable(false);
        saldo.setBackground(new java.awt.Color(204, 255, 204));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("Saldo");

        jLabel14.setText("Total retirado");

        totalRetiros.setEditable(false);
        totalRetiros.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(ckPin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(chkRetiro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retiro)
                            .addComponent(saldo)
                            .addComponent(totalRetiros)
                            .addComponent(jtfMainAccount, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(10, 10, 10))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pinPago)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(ckPin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pinPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMainAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(totalRetiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkRetiro))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 102));

        jtfDarVueltas.setEditable(false);
        jtfDarVueltas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfDarVueltas.setForeground(new java.awt.Color(255, 51, 0));
        jtfDarVueltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDarVueltasKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Cambio $");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtfValor.setEditable(false);
        jtfValor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfValor.setForeground(new java.awt.Color(255, 0, 0));
        jtfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfValorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Valor");

        jtfCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCreditoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCreditoKeyTyped(evt);
            }
        });

        jLabel5.setText("Credito");

        jLabel4.setText("Debito");

        jLabel3.setText("Efectivo");

        jtfEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfEfectivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfEfectivoKeyTyped(evt);
            }
        });

        jtfDebito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDebitoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDebitoKeyTyped(evt);
            }
        });

        jLabel2.setText("Forma de Pago");

        jtaDireccion.setEditable(false);
        jtaDireccion.setColumns(20);
        jtaDireccion.setRows(5);
        jScrollPane1.setViewportView(jtaDireccion);

        jLabel8.setText("Dolar hoy");

        jtfDolarHoy.setText("0");
        jtfDolarHoy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDolarHoyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDolarHoyKeyTyped(evt);
            }
        });

        jLabel9.setText("Cantidad");

        jtfCantidadDolar.setText("0");
        jtfCantidadDolar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCantidadDolarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCantidadDolarKeyTyped(evt);
            }
        });

        jLabel10.setText("Pesos");

        jtfDolarPesos.setEditable(false);
        jtfDolarPesos.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDarVueltas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDolarHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCantidadDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jtfDolarPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfDolarHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtfCantidadDolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtfDolarPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfValor))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDarVueltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29))
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imp.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setText("Crear servicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Agst 05 de 16 V 2.0.1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(msError, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton2)
                        .addGap(63, 63, 63)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(732, 732, 732))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(msjError, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel7))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msjError)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jtfCantidadDolarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCantidadDolarKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfCantidadDolarKeyTyped

    private void jtfCantidadDolarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCantidadDolarKeyReleased
        // TODO add your handling code here:
        dolarPesos();
    }//GEN-LAST:event_jtfCantidadDolarKeyReleased

    private void jtfDolarHoyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDolarHoyKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfDolarHoyKeyTyped

    private void jtfDolarHoyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDolarHoyKeyReleased
        // TODO add your handling code here:
        dolarPesos();
    }//GEN-LAST:event_jtfDolarHoyKeyReleased

    private void jtfDebitoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDebitoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        String enter = "enter";
        int condition = JComponent.WHEN_FOCUSED;
        InputMap iMap = jtfDebito.getInputMap(condition);
        ActionMap aMap = jtfDebito.getActionMap();

        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), enter);
        aMap.put(enter, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                generarServicio();
            }
        });
    }//GEN-LAST:event_jtfDebitoKeyTyped

    private void jtfDebitoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDebitoKeyReleased
        // TODO add your handling code here:
        try {
            Integer debito = null;
            Integer valorViaje = new Integer(tiquete.getValor());
            if (jtfDebito.getText() != null && !jtfDebito.getText().isEmpty()) {
                if (jtfDebito.getText().length() > 7) {
                    jtfDebito.setText("0");
                }
                debito = new Integer(jtfDebito.getText());

            } else {
                debito = new Integer("0");
            }

            if (debito > valorViaje) {
                jtfDebito.setText("" + valorViaje);
                debito = new Integer(jtfDebito.getText());
            }

            Integer EFECTIVO = valorViaje - debito;

            jtfEfectivo.setText(EFECTIVO.toString());
            jtfCredito.setText("" + 0);
            jtfDarVueltas.setText("" + 0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jtfDebitoKeyReleased

    private void jtfEfectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEfectivoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        String enter = "enter";
        int condition = JComponent.WHEN_FOCUSED;
        InputMap iMap = jtfEfectivo.getInputMap(condition);
        ActionMap aMap = jtfEfectivo.getActionMap();

        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), enter);
        aMap.put(enter, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                generarServicio();
            }
        });
    }//GEN-LAST:event_jtfEfectivoKeyTyped

    private void jtfEfectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEfectivoKeyReleased
        // TODO add your handling code here:
        try {
            Integer efectivo = null;
            Integer valorViaje = Helper.getNumberInt(jtfValor.getText());
            if (jtfEfectivo.getText() != null && !jtfEfectivo.getText().isEmpty()) {
                if (jtfEfectivo.getText().length() > 7) {
                    jtfEfectivo.setText("0");
                }
                efectivo = Helper.getNumberInt(jtfEfectivo.getText());
            } else {
                efectivo = Helper.getNumberInt("0");
            }
            Integer DAR_CAMBIO = efectivo - valorViaje;
            if (DAR_CAMBIO < 0) {
                DAR_CAMBIO = 0;
            }

            jtfDarVueltas.setText(formateador.format(DAR_CAMBIO));
            jtfDebito.setText("" + 0);
            jtfCredito.setText("" + 0);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jtfEfectivoKeyReleased

    private void jtfCreditoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCreditoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        String enter = "enter";
        int condition = JComponent.WHEN_FOCUSED;
        InputMap iMap = jtfCredito.getInputMap(condition);
        ActionMap aMap = jtfCredito.getActionMap();

        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), enter);
        aMap.put(enter, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                generarServicio();
            }
        });
    }//GEN-LAST:event_jtfCreditoKeyTyped

    private void jtfCreditoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCreditoKeyReleased
        // TODO add your handling code here:

        try {
            Integer debito = null;
            Integer valorViaje = new Integer(tiquete.getValor());
            if (jtfCredito.getText() != null && !jtfCredito.getText().isEmpty()) {
                if (jtfCredito.getText().length() > 7) {
                    jtfCredito.setText("0");
                }
                debito = new Integer(jtfCredito.getText());

            } else {
                debito = new Integer("0");
            }

            if (debito > valorViaje) {
                jtfCredito.setText("" + valorViaje);
                debito = new Integer(jtfCredito.getText());
            }
            Integer EFECTIVO = valorViaje - debito;
            jtfEfectivo.setText(EFECTIVO.toString());
            jtfDebito.setText("" + 0);
            jtfDarVueltas.setText("" + 0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jtfCreditoKeyReleased

    private void jtfDarVueltasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDarVueltasKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDarVueltasKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (!(sitios.getIdSitio().equals("8") && ckPin.isSelected())) {
            Integer mySaldo = Helper.getNumberInt(saldo.getText());
            Integer valorRetiro = Helper.getNumberInt(retiro.getText());

            Integer queda = mySaldo - valorRetiro;
            if (queda >= 0) {
                generarServicio();
            } else {
                JOptionPane.showMessageDialog(null, "Favor verificar el valor del servicio");
            }
        } else {
            generarServicio();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void retiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_retiroKeyTyped
        // TODO add your handling code here:

        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        } else {
            calcularRetiro();
        }

    }//GEN-LAST:event_retiroKeyTyped

    private void retiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_retiroKeyReleased
        // TODO add your handling code here:

        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        } else {
            calcularRetiro();
        }
    }//GEN-LAST:event_retiroKeyReleased

    private void chkRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRetiroActionPerformed
        // TODO add your handling code here:

        if (chkRetiro.isSelected()) {
            retiro.setEditable(true);
            retiro.setEnabled(true);

            if (ckPin.isSelected()) {
                calcularRetiro();
            } else {
                // limpiarRetiro();
            }
        } else {
            retiro.setEditable(false);
            retiro.setEnabled(false);
        }
    }//GEN-LAST:event_chkRetiroActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        jtfDarVueltas.setText("0");
        jtfValor.setText("0");
        jtfCredito.setText("0");
        jtfDebito.setText("0");
        jtfEfectivo.setText("0");
        jButton1.setEnabled(true);
        chkRetiro.setEnabled(false);

        if ((this.sitios.getIdSitio().equals("8")) && (this.ckPin.isSelected())) {
            String ping = this.pinPago.getText();
            if ((this.pinPago.getText() != null) && (!this.pinPago.getText().isEmpty()) && (this.pinPago.getText().length() > 0)) {
                RootPaneContainer root = (RootPaneContainer) this.getRootPane().getTopLevelAncestor();
                root.getGlassPane().setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                root.getGlassPane().setVisible(true);
                String JSON = Helper.getJSONConsultModipay(this.cajeros.getIdUsuario(), this.cajeros.getUsuario(), this.pinPago.getText(), this.cajeros.getIdSitio());
                String jsonValidaModipay = new WebserviceConnection(host, port).getStatusAccount(JSON);
                System.out.println("RTA: " + jsonValidaModipay);
                Ticket tk = (Ticket) this.gson.fromJson(jsonValidaModipay, Ticket.class);
                if (tk.getError().equals("ok")) {

                    configRetiro(tk.getDisponible(), tk.getValorTotal(), tk.getRetiros());

                } else {
                    jButton1.setEnabled(false);
                    this.pinPago.setBackground(Color.red);
                    chkRetiro.setEnabled(false);
                    retiro.setEditable(false);
                    this.retiro.setBackground(Color.red);
                    retiro.setText("");
                    saldo.setText("");
                    totalRetiros.setText(tk.getRetiros());
                    jtfMainAccount.setText("");

                }
                msError.setText(tk.getMsjError());

                root.getGlassPane().setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            } else {
                pinPago.setBackground(Color.red);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pinPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinPagoKeyTyped
        // TODO add your handling code here:
        jButton1.setEnabled(false);
        this.pinPago.setBackground(Color.red);
        chkRetiro.setEnabled(false);
        retiro.setEditable(false);
        retiro.setText("");
    }//GEN-LAST:event_pinPagoKeyTyped

    private void pinPagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinPagoKeyPressed
        // TODO add your handling code here:
        jButton1.setEnabled(false);
        this.pinPago.setBackground(Color.red);
        chkRetiro.setEnabled(false);
        retiro.setEditable(false);
        retiro.setText("");
    }//GEN-LAST:event_pinPagoKeyPressed

    private void pinPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinPagoActionPerformed

    private void ckPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPinActionPerformed
        // TODO add your handling code here:
        chkRetiro.setEnabled(false);
        if (ckPin.isSelected()) {
            pinPago.setEnabled(true);
            pinPago.setEditable(true);
            jtfEfectivo.setText("");
            jtfCredito.setText("");
            jtfDebito.setText("");
            jtfEfectivo.setEditable(false);
            jtfCredito.setEditable(false);
            jtfDebito.setEditable(false);
            pinPago.setEditable(true);
            pinPago.setBackground(Color.yellow);
            jtfDebito.setBackground(Color.white);
            jtfCredito.setBackground(Color.white);
            jtfEfectivo.setBackground(Color.white);
            jButton1.setEnabled(false);
            jButton3.setEnabled(true);
            saldo.setText("");
        } else {
            jtfEfectivo.setText("");
            jtfMainAccount.setText("");
            jtfCredito.setText("");
            jtfDebito.setText("");
            jtfEfectivo.setEditable(true);
            jtfCredito.setEditable(true);
            jtfDebito.setEditable(true);
            pinPago.setText("");
            pinPago.setEditable(false);
            pinPago.setBackground(Color.white);
            jButton3.setEnabled(false);
            jtfDebito.setBackground(Color.yellow);
            jtfCredito.setBackground(Color.yellow);
            jtfEfectivo.setBackground(Color.yellow);
            jButton1.setEnabled(true);
            saldo.setText("");

        }
        limpiarRetiro();
    }//GEN-LAST:event_ckPinActionPerformed

    private void jtfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfValorActionPerformed

    private void retiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retiroActionPerformed
    boolean calcularRetiro() {

        Integer mySaldo = Helper.getNumberInt(saldo.getText());
        Integer valorRetiro = Helper.getNumberInt(retiro.getText());

        Integer queda = mySaldo - valorRetiro;
        System.out.println("retiro de $" + valorRetiro + " de la cuenta por $" + mySaldo + " =>  " + queda);
        if ((queda >= 0)) {
            jtfDarVueltas.setText("0");
            //saldo.setText(queda.toString());
            jtfValor.setText(valorRetiro.toString());
            return true;
        } else {
            if (queda < 0) {
                //saldo.setText("0");
                retiro.setText("0");
            }
            return false;
        }

    }

    void limpiarRetiro() {
        retiro.setText("");
        jtfValor.setText("");
        saldo.setText("");
        jtfDarVueltas.setText("0");
    }

    void configRetiro(String disponible, String valorTotal, String retiros) {
        retiro.setText(disponible);
        jtfValor.setText(valorTotal);
        saldo.setText(disponible);
        jtfDarVueltas.setText("0");
        jtfMainAccount.setText(valorTotal);
        jtfValor.setText(disponible);
        jtfCredito.setText(disponible);
        totalRetiros.setText(retiros);
        jtfDebito.setText("0");
        jtfEfectivo.setText("0");
        jButton1.setEnabled(true);
        pinPago.setBackground(Color.white);
        chkRetiro.setEnabled(true);
        retiro.setEditable(true);
        retiro.setText(disponible);
        this.jtfDarVueltas.setText("0");
    }

    public CajerosAero leerCajero(CajerosAero ca, Ticket tk, Servicios srv, boolean isWS, Sitios place, String host, Integer port, Properties properties) {
        this.cajeros = ca;
        this.tiquete = tk;
        this.srv = srv;
        this.isWS = isWS;
        this.sitios = place;
        this.base = tk.getBase();
        jtfValor.setText(tk.getValor());
        jtaDireccion.setText(tk.getDestino());
        this.host = host;
        this.port = port;
        this.properties = properties;

        jtfEfectivo.requestFocusInWindow();

        if (sitios.getIdSitio().equals("8")) {
            jtaDireccion.setEditable(true);
            arg = sitios.getNombre().split("\\|");
            ckPin.setEnabled(true);
        } else {
            arg = sitios.getNombre().split("\\|");
            ckPin.setEnabled(false);
        }
        userInformation.setText(ca.getNombre() + " en " + sitios.getNombre());

        jtfEfectivo.setText(tk.getValor());

        return cajeros;
    }

    public void generarServicio() {
        Servicios srv2 = new Servicios();
        String fuec = "";
        try {
            Object obj[] = null;

            Integer efectivoCliente = Helper.isOkJTF(jtfEfectivo);
            Integer debitoCliente = Helper.isOkJTF(jtfDebito);
            Integer creditoCliente = Helper.isOkJTF(jtfCredito);

            Integer dineroCliente = efectivoCliente + debitoCliente + creditoCliente;

            if (dineroCliente < Helper.getNumberInt(jtfValor.getText())) {
                JOptionPane.showMessageDialog(null, "No hay suficiente dinero para crear el servicio");
            } else {
                String error = "no";

                Integer valorTotal = Helper.getNumberInt(srv.getValor());
                Integer myBase = Helper.getNumberInt(base);

                String destino = Helper.eliminarBarusar(srv.getAddres());

                String obs = Helper.eliminarBarusar(tiquete.getControl());

                obj = cargarTK(destino, tiquete.getNombre(), tiquete.getNit(), cajeros);

                if (obj != null) {

                    tiquete = (Ticket) obj[0];
                    tiquete.setControl(obs);

                    srv = (Servicios) obj[1];
                    String json = (String) obj[2];
                    srv.setValorD("" + debitoCliente);
                    srv.setValorC("" + creditoCliente);
                    srv.setBase(myBase.toString());

                    srv.setValorE("" + (efectivoCliente - Helper.getNumberInt(jtfDarVueltas.getText().replace(".", ""))));
                    srv.setSitio(sitios);
                    srv.setValor(jtfValor.getText());

                    tiquete.setValor(srv.getValor());
                    tiquete.setOrigen(sitios.getDireccion());
                    tiquete.setDestino(jtaDireccion.getText().trim());

                    if (tiquete != null) {
                        int response = 1;
                        if (!validarPlaca) {
                            response = 0;

                            PLACA = "AAA000";
                            srv.setAutoPlaca(PLACA);
                            //srv.setComprob(arg[0]);
                            srv.setComprob("TES");
                            tiquete.setFecha(Helper.fechaActual(new Date()));
                        } else {
                            response = JOptionPane.showConfirmDialog(null, "Conductor: " + tiquete.getCcConductor1() + " " + tiquete.getNombreConductor1() + " " + tiquete.getApellidoConductor1() + "\n\n\n\n\n\n", "Es el conductor?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        }
                        if (response == JOptionPane.NO_OPTION) {
                            error = "change";
                        } else {
                            error = "ok";
                            srv.setCajero(cajeros);
                            String NIT = srv.getNit();
                            String GRABADOR = srv.getGrabador();
                            String VALOR = srv.getValor();
                            String FECHA = Helper.getColCurrentTime();
                            String NOMBRE = tiquete.getNombre();
                            String ADDRESS = srv.getAddres();
                            String USUARIOS = cajeros.getUsuario();
                            String TIPO_PAGO = tiquete.getTipoPago();
                            String COMPROBANTE = srv.getComprob();
                            String CIERRE = srv.getCierre();

                            tiquete.setValorD(Helper.getString(srv.getValorD()));
                            tiquete.setValorC(Helper.getString(srv.getValorC()));
                            tiquete.setValorE(Helper.getString(srv.getValorE()));

                            String valorD = srv.getValorD();
                            String valorC = srv.getValorC();
                            String valorE = srv.getValorE();
                            String sitio = srv.getSitio().getIdSitio();
                            String retiroParcial = chkRetiro.isSelected() ? "true" : "false";

                            // JOptionPane.showMessageDialog(null, "" + PLACA + " = " + NIT + " = " + GRABADOR + " = " + cajeros.getIdUsuario() + " = " + VALOR + " = " + FECHA + " = " + NOMBRE + " = " + ADDRESS + " = " + USUARIOS + " = "
                            //         + TIPO_PAGO + " = " + COMPROBANTE + " = " + CIERRE + " = " + valorD + " = " + valorE + " = " + valorC + " = " + cajeros.getIdSitio());
                            String JSON = Helper.getJSONCrearSrv(PLACA, NIT, GRABADOR, cajeros.getIdUsuario(),
                                    VALOR, FECHA, NOMBRE, ADDRESS, USUARIOS,
                                    TIPO_PAGO, COMPROBANTE, CIERRE,
                                    valorD, valorE, valorC, cajeros.getIdSitio(),
                                    arg[4],
                                    pinPago.getText(),
                                    retiroParcial,
                                    tiquete.getNumeroInterno());

                            tiquete.setPlaca(PLACA);
                            tiquete.setNit(NIT);
                            tiquete.setGrabador(GRABADOR);
                            tiquete.setUsuario(cajeros);
                            tiquete.setIdUsuario(cajeros.getIdUsuario());
                            tiquete.setValor(VALOR);

                            tiquete.setNombre(NOMBRE);
                            tiquete.setDireccion(ADDRESS);
                            tiquete.setUsuarios(USUARIOS);
                            tiquete.setUsuarios(USUARIOS);
                            tiquete.setTipoPago(TIPO_PAGO);
                            tiquete.setComprob(COMPROBANTE);
                            tiquete.setCierre("0");
                            tiquete.setValorD(valorD);
                            tiquete.setValorE(valorE);
                            tiquete.setValorC(valorC);
                            tiquete.setSitio(cajeros.getIdSitio());
                            tiquete.setIndProc(arg[4]);
                            tiquete.setTransaccion(pinPago.getText());
                            tiquete.setRetiroParcial(retiroParcial);

                            String sCrearSrv = "[" + Helper.nuevoCrearSrv(tiquete) + "]";
                            System.out.println("SEND: " + sCrearSrv);
                            //hsa String jsonCrearSrv = new WebserviceConnection(host, port).getStatusAccount(JSON);
                            String jsonCrearSrv = new WebserviceConnection(host, port).getStatusAccount(sCrearSrv);

                            /*if (Helper.isOK(JSON)) {
                             RtaDTO obj2 = gson.fromJson(jsonCrearSrv, RtaDTO.class);
                             for (JsonDTO p : obj2.getAlertas()) {
                             if (p.getError().equals("ok")) {
                             srv2.setId(p.getId());
                             srv2.setNumeroFactura(p.getId());
                             srv2.setFecha(new Helper().getColCurrentTime());

                             fuec = p.getFuec();
                             error = "ok";
                             }
                             }
                             }*/
                            if (Helper.isOK(JSON)) {
                                JsonDTO obj2 = gson.fromJson(jsonCrearSrv, JsonDTO.class);

                                if (obj2.getError().equals("ok")) {
                                    Ticket p = obj2.getTiquete();
                                    srv2.setId(p.getId().toString());
                                    srv2.setNumeroFactura(p.getId().toString());
                                    srv2.setFecha(new Helper().getColCurrentTime());

                                    // fuec = p.getFuec();
                                    error = "ok";
                                }

                            }
                        }
                    }

                    if (error == "change") {
                        new MensajeTmp().createAndShowGui("Debe elegir otro vehiculo");
                    } else {
                        if (error == "no") {
                            new MensajeTmp().createAndShowGui("No hay respuesta desde el servidor para crear servicios, Intentelo nuevamente");
                        } else {
                            byte[] bytes = null;
                            byte[] bytes2 = null;

                            tiquete.setId(new Long(srv2.getNumeroFactura()));
                            //tiquete.setFecha(Helper.toDateYYMMDDHHMM(srv2.getFecha()));

                            tiquete.setInfoRuta(sitios.getDireccion().split("\\|")[1] + " hasta " + jtaDireccion.getText().trim());

                            comprob = srv.getComprob();
                            if (!new isProduccion().isProduccion().equals("srvapp-desarrollo.losunos.net")) {
                                //  new ExecuteCargarSrvContable(comprob).execute();

                            }

                            tiquete.setNumeroLargo(getNumeroLargo(tiquete));
                            //tiquete.setFecha(Helper.toDateYYYYMMDD(tiquete.getFecha()));
                            //tiquete.setFechaFin(Helper.toDateYYYYMMDD(tiquete.getFechaFin()));
                            // if (sitios.getIdSitio().equals("8")) {

                            //}
                            //new WebserviceConnection(host, port).getStatusAccount(Helper.registroFactura(tiquete));
                            if (validarPlaca) {
                                generePOST(tiquete.getId().toString());//impresion impresora POST
                                genereFUEC2(tiquete);//generar PDF

                            } else {
                                // generar qr nuevo
                                generePOST_QR(tiquete.getId().toString());//impresion impresora POST
                            }
                        }

                        tiquete = null;
                        dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Vehiculo no encontrado y/o BLOQUEADO");
                    // tiquete = null;
                }
            }
        } catch (Exception e) {
            // tiquete = null;
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error vehiculo no disponible");
        }
    }

    public void generarServicio2() {
        Servicios srv2 = new Servicios();
        String fuec = "";
        try {
            Object obj[] = null;

            Integer efectivoCliente = Helper.isOkJTF(jtfEfectivo);
            Integer debitoCliente = Helper.isOkJTF(jtfDebito);
            Integer creditoCliente = Helper.isOkJTF(jtfCredito);

            Integer dineroCliente = efectivoCliente + debitoCliente + creditoCliente;

            if (dineroCliente < Helper.getNumberInt(jtfValor.getText())) {
                JOptionPane.showMessageDialog(null, "No hay suficiente dinero para crear el servicio");
            } else {
                String error = "no";

                Integer valorTotal = Helper.getNumberInt(srv.getValor());
                String destino = Helper.eliminarBarusar(srv.getAddres());

                obj = cargarTK(destino, tiquete.getNombre(), tiquete.getNit(), cajeros);

                tiquete = (Ticket) obj[0];
                srv = (Servicios) obj[1];
                String json = (String) obj[2];
                srv.setValorD("" + debitoCliente);
                srv.setValorC("" + creditoCliente);
              

                srv.setValorE("" + (efectivoCliente - Helper.getNumberInt(jtfDarVueltas.getText().replace(".", ""))));
                srv.setSitio(sitios);
                srv.setValor(jtfValor.getText());
                tiquete.setValor(srv.getValor());
                tiquete.setOrigen(sitios.getDireccion());
                tiquete.setDestino(jtaDireccion.getText().trim());
            

                if (tiquete != null) {
                    int response = 1;
                    if (!validarPlaca) {
                        response = 0;
                    } else {
                        response = JOptionPane.showConfirmDialog(null, "Conductor___: " + tiquete.getCcConductor1() + " " + tiquete.getNombreConductor1() + " " + tiquete.getApellidoConductor1() + "\n\n\n\n\n\n", "Es el conductor___?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                    }

                    if (response == JOptionPane.NO_OPTION) {
                        error = "change";
                    } else {
                        error = "ok";
                        srv.setCajero(cajeros);
                        String NIT = srv.getNit();
                        String GRABADOR = srv.getGrabador();
                        String VALOR = srv.getValor();
                        String FECHA = Helper.getColCurrentTime();
                        String NOMBRE = tiquete.getNombre();
                        String ADDRESS = srv.getAddres();
                        String USUARIOS = srv.getUsuarios().getUsuario();
                        String TIPO_PAGO = tiquete.getTipoPago();
                        String COMPROBANTE = srv.getComprob();
                        String CIERRE = srv.getCierre();

                        String valorD = srv.getValorD();
                        String valorC = srv.getValorC();
                        String valorE = srv.getValorE();
                        String sitio = srv.getSitio().getIdSitio();
                        String retiroParcial = chkRetiro.isSelected() ? "true" : "false";
                        // JOptionPane.showMessageDialog(null, "" + PLACA + " = " + NIT + " = " + GRABADOR + " = " + cajeros.getIdUsuario() + " = " + VALOR + " = " + FECHA + " = " + NOMBRE + " = " + ADDRESS + " = " + USUARIOS + " = "
                        //         + TIPO_PAGO + " = " + COMPROBANTE + " = " + CIERRE + " = " + valorD + " = " + valorE + " = " + valorC + " = " + cajeros.getIdSitio());
                        String JSON = Helper.getJSONCrearSrv(PLACA, NIT, GRABADOR, cajeros.getIdUsuario(), VALOR, FECHA, NOMBRE, ADDRESS, USUARIOS,
                                TIPO_PAGO, COMPROBANTE, CIERRE, valorD, valorE, valorC, cajeros.getIdSitio(), arg[4], pinPago.getText(), retiroParcial, tiquete.getNumeroInterno());

                        tiquete.setId(Long.MIN_VALUE);

                        String jsonCrearSrv = new WebserviceConnection(host, port).getStatusAccount(JSON);

                        if (Helper.isOK(JSON)) {
                            RtaDTO obj2 = gson.fromJson(jsonCrearSrv, RtaDTO.class);
                            for (JsonDTO p : obj2.getAlertas()) {
                                if (p.getError().equals("ok")) {
                                    srv2.setId(p.getId());
                                    srv2.setNumeroFactura(p.getId());
                                    srv2.setFecha(new Helper().getColCurrentTime());

                                    fuec = p.getFuec();
                                    error = "ok";
                                }
                            }
                        }
                    }
                }

                if (error == "change") {
                    new MensajeTmp().createAndShowGui("Debe elegir otro vehiculo");
                } else {
                    if (error == "no") {
                        new MensajeTmp().createAndShowGui("No hay respuesta desde el servidor para crear servicios, Intentelo nuevamente");
                    } else {
                        byte[] bytes = null;
                        byte[] bytes2 = null;

                        tiquete.setId(new Long(srv2.getNumeroFactura()));
                        //tiquete.setFecha(Helper.toDateYYMMDDHHMM(srv2.getFecha()));
                        tiquete.setInfoRuta(sitios.getDireccion().split("\\|")[1] + " hasta " + jtaDireccion.getText().trim());

                        comprob = srv.getComprob();
                        if (!new isProduccion().isProduccion().equals("srvapp-desarrollo.losunos.net")) {
                            new ExecuteCargarSrvContable(comprob).execute();

                        }

                        // generePOST(tiquete.getId().toString());//impresion impresora POST
                        genereFUEC(tiquete.getId().toString(), fuec);//generar PDF
                    }
                    dispose();
                }
                System.out.println("cerrando la ventana....2");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void generePOST_QR(String a) {
        try {
            Properties pr = new Properties();
            pr.load(new FileReader(new InitHelper().getCurrentWorkingDirectory() + "/factura.properties"));

            isWS = new Boolean(pr.getProperty("WS"));
            pr.load(new FileReader(getCurrentWorkingDirectory() + "/configurar.properties"));
            String[] CP = new String[]{"===COPIA EMPRESA===", "===COPIA CONDUCTOR===", "===COPIA USUARIO==="};
            for (int i = 0; i < 1; i++) {

                byte[] bytes = new CrearDocumento().generarFactura_qr(tiquete, sitios, pr, CP[i]);
                PrintPdf printPDFFile = new PrintPdf(bytes, "Test Print PDF");
                printPDFFile.print();
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al imprimir el archivo, favor reimprimirlo nuevamente");
        }
    }

    public void generePOST(String a) {
        try {
            Properties pr = new Properties();
            pr.load(new FileReader(new InitHelper().getCurrentWorkingDirectory() + "/factura.properties"));

            isWS = new Boolean(pr.getProperty("WS"));
            pr.load(new FileReader(getCurrentWorkingDirectory() + "/configurar.properties"));
            String[] CP = new String[]{"===COPIA EMPRESA===", "===COPIA CONDUCTOR===", "===COPIA USUARIO==="};
            for (int i = 0; i < 3; i++) {
                byte[] bytes = new CrearDocumento().generarFactura(tiquete, sitios, pr, CP[i]);
                PrintPdf printPDFFile = new PrintPdf(bytes, "Test Print PDF");
                printPDFFile.print();
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al imprimir el archivo, favor reimprimirlo nuevamente");
        }
    }

    public void genereFUEC(String consecutivo, String fuec) {
        try {
            Properties pr = new Properties();
            pr.load(new FileReader(new InitHelper().getCurrentWorkingDirectory() + "/factura.properties"));
            isWS = new Boolean(pr.getProperty("WS"));
            pr.load(new FileReader(getCurrentWorkingDirectory() + "/configurar.properties"));

            byte[] bytes2 = new CrearDocumento1().generarFactura2(tiquete, pr, "Impreso", tiquete.getUsuario().getUsuario(), consecutivo, fuec);
            String path = new InitHelper().getCurrentWorkingDirectory() + "/fact_" + tiquete.getNumeroLargo() + "_.pdf";
            Desktop.getDesktop().open(new File(path));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al imprimir el archivo, favor reimprimirlo nuevamente");
        }
    }

    public void genereFUEC2(Ticket tiket) {
        try {
            Properties pr = new Properties();
            pr.load(new FileReader(new InitHelper().getCurrentWorkingDirectory() + "/factura.properties"));
            isWS = new Boolean(pr.getProperty("WS"));
            pr.load(new FileReader(getCurrentWorkingDirectory() + "/configurar.properties"));

            String path = new InitHelper().getCurrentWorkingDirectory() + "/" + tiket.getConsecutivo() + "_fac_nuevo.pdf";
            byte[] bytes2 = new FuecTool().crearFuec(tiket, path);

            Desktop.getDesktop().open(new File(path));

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al imprimir el archivo, favor reimprimirlo nuevamente");
        }
    }

    class ExecuteCargarSrvContable extends SwingWorker {

        String comprob;

        ExecuteCargarSrvContable(String values) {
            this.comprob = values;
        }
        boolean isContinue = true;

        @Override
        protected Object doInBackground() {
            try {

                System.out.println("inicia trabajo se cargue asi:  " + (30000) + " : " + new Helper().getColCurrentTime());
                //Thread.sleep(30000 * 2);
                actualizarContaLocal(null, comprob);
                System.out.println("finalizar trabajo se cargue asi:  " + (30000) + " : " + new Helper().getColCurrentTime());

            } catch (Exception ex) {
            }
            return 0;
        }
    }

    public String actualizarContaLocal(String initial, String comprob) throws Exception {

        Properties configFile = new Principal().readProperties();
        host = configFile.getProperty("HOST");
        port = Helper.getNumberInt(configFile.getProperty("PORT"));
        Properties pr2 = new Properties();
        pr2.load(new FileReader(getCurrentWorkingDirectory() + "/factura.properties"));

        String _JSON = Helper.getJSONConsultaSrv(comprob);
        System.out.println("jsonSend:  " + _JSON);
        String RTA_CARGUE = new WebserviceConnection(host, port).getStatusAccount(_JSON);

        if (initial != null) {
            if (Helper.isOK(RTA_CARGUE)) {
                RtaDTO obj = gson.fromJson(RTA_CARGUE, RtaDTO.class);
                if (obj.getError().equals("ok") && obj.getAlertas() != null && obj.getAlertas().size() > 0) {
                    return "" + obj.getAlertas().size();
                }
            }
            return "0";
        } else {

            Helper.rw("ENTRADA: inicia cargue");
            boolean isAllOk = false;
            do {
                if (Helper.isOK(RTA_CARGUE)) {
                    isAllOk = true;
                    RtaDTO obj = gson.fromJson(RTA_CARGUE, RtaDTO.class);
                    if (obj.getError().equals("ok") && obj.getAlertas() != null && obj.getAlertas().size() > 0) {
                        Helper.rw("SEND:  " + obj.getAlertas().size());
                        String RTA_CARGUE_REMOTE = new WebserviceConnection(host, port).getStatusAccountRemote200_91_204_38(RTA_CARGUE);
                        RtaDTO UPDATED = gson.fromJson(RTA_CARGUE_REMOTE, RtaDTO.class);
                        Helper.rw("END UPDATED REMOTE:  " + RTA_CARGUE_REMOTE);
                        if (UPDATED.getError().equals("ok")) {
                            String rta = new WebserviceConnection(host, port).getStatusAccount(RTA_CARGUE_REMOTE);
                            Helper.rw("END UPDATED VPS:  " + RTA_CARGUE_REMOTE);
                            // new FileUtilities().escribirRegistro("RESPUESTA DE ACTUALIZACION ", rta);
                        }
                        Thread.sleep(5000);
                        RTA_CARGUE = new WebserviceConnection(host, port).getStatusAccount(_JSON);

                    } else {
                        Helper.rw("No hay sincronizacion");
                        return "ok";
                    }

                } else {
                    isAllOk = false;
                    Helper.rw("No hay sincronizacion");
                    return "No hay sincronizacion, ";
                }

            } while (Helper.isOK(RTA_CARGUE));

        }
        return "ok";
    }

    public Object[] cargarTK(String direccion, String nombre, String nit, CajerosAero user) {

        long precio = Helper.getNumberLong(jtfValor.getText());
        try {
           // Servicios servicio = new Servicios();

            Properties pr = new Properties();
            pr.load(new FileReader(getCurrentWorkingDirectory() + "/configurar.properties"));

            isWS = new Boolean(pr.getProperty("WS"));
            Properties pr2 = new Properties();
            pr2.load(new FileReader(getCurrentWorkingDirectory() + "/factura.properties"));
            String VJS = arg[0];

            String INGRESOS = pr2.getProperty("INGRESOS");
            boolean ingresarPlacaManual = false;
            System.out.println("isWS " + isWS);

            tiquete.setDestino(direccion);
            tiquete.setId(Helper.getNumberLong(srv.getId()));
            tiquete.setValor("" + precio);
            tiquete.set2300("0");
            tiquete.setDistancia(0);
            tiquete.setFecha(Helper.fechaActual(Helper.getColCurrentTime2()));
            tiquete.setFechaFin(Helper.fechaActual(Helper.addDay()));

            tiquete.setUsuario(user);
            tiquete.setTipoPago("005");
            tiquete.setConductor("No DISP");
           // servicio.setAddres(direccion + "|" + nombre + "|" + nit);

            String nits = null;
            String _nits[] = null;
            String rta = "";
            int oportunidades = 1;
            ingresarPlacaManual = true;

            if (!validarPlaca) {

                Object[] obj2 = new Object[3];
                obj2[0] = tiquete;
                obj2[1] = srv;
                obj2[2] = "";
                return obj2;
            }

            while (nits == null && PLACA != null && oportunidades <= 3) {
                PLACA = JOptionPane.showInputDialog(this, "Ingrese placa" + rta, "IMPRIMIR SERVICIO PLACA", JOptionPane.INFORMATION_MESSAGE);

                //inicia
                if (false) {//cmabiar por true para ir a la version anterior
                    _nits = new LoadPlaca().cargarNits2(PLACA); //lectura desde un archivo local    
                } else {

                    boolean isOkContainer = false;

                    String entradaPlaca = new WebserviceConnection(host, port).getStatusAccount(Helper.getJSONBuscarPlacaContainer(PLACA));

                    System.out.println("RTA_VPS: " + entradaPlaca);
                    if (Helper.isOK(entradaPlaca)) {
                        Ticket obj = gson.fromJson(entradaPlaca, Ticket.class);
                        if (obj != null && obj.getError().equals("no")) {
                            isOkContainer = true;
                            // no buscar en RTA  entradaPlaca = new WebserviceConnection(properties.getProperty("HOST_RTA"), Helper.getNumberInt(properties.getProperty("PORT_RTA"))).getStatusAccountRemote200_91_204_38(Helper.getJSONBuscarPlaca(PLACA));
                            System.out.println("RTA_Nuevo_crear_srv:" + entradaPlaca);
                        }
                    }

                    if (Helper.isOK(entradaPlaca)) {
                        Ticket obj = gson.fromJson(entradaPlaca, Ticket.class);
                        if (obj != null && obj.getError().equals("ok")) {
                            nits = obj.getNit();
                            System.out.println("values: " + obj.getNit());
                            Persona conductor1 = new Persona();
                            tiquete.setNitPago(obj.getNitPago());
                            tiquete.setNit(obj.getNitPropieta());
                            tiquete.setObjecto(obj.getObjecto());
                            tiquete.setEmpresa(obj.getEmpresa());
                            tiquete.setNitPagador(obj.getNitPagador());

                            Object driver = null;
                            boolean mostrarSelect = false;

                            if (obj.getPersonas() != null && obj.getPersonas().size() > 0) {
                                Object[] conductor = new Object[obj.getPersonas().size()];
                                int i = 0;

                                for (Persona p : obj.getPersonas()) {
                                    conductor[i] = p.getCcConductor1()
                                            + "|" + p.getNombreConductor1()
                                            + "|" + p.getApellidoConductor1()
                                            + "|" + p.getLicenciaConductor1()
                                            + "|" + p.getVigenciaConductor1();

                                    tiquete.setEmpresaVehiculo(p.getEmpresaVehiculo());
                                    System.out.println("el carro es de ");
                                    i++;
                                }
                                tiquete.setPersonas(obj.getPersonas());
                                if (i > 1) {
                                    driver = JOptionPane.showInputDialog(null, "Seleccionar un Conductor",
                                            "CODUCTORES", JOptionPane.QUESTION_MESSAGE, null,
                                            conductor, "Seleccione");
                                } else {
                                    driver = conductor[0];
                                }

                                if (driver != null) {
                                    String val[] = driver.toString().split("\\|");
                                    tiquete.setCcConductor1(validaArray(val, 0));
                                    tiquete.setNombreConductor1(validaArray(val, 1));
                                    tiquete.setApellidoConductor1(validaArray(val, 2));
                                    tiquete.setLicenciaConductor1(validaArray(val, 3));
                                    tiquete.setVigenciaConductor1(validaArray(val, 4));
                                }
                                //JOptionPane.showMessageDialog(null, validaArray(val, 0) + " " + validaArray(val, 1) + " " + validaArray(val, 2) + " " + validaArray(val, 3) + " " + validaArray(val, 4));
                                tiquete.setNitConductor(getString(obj.getNitConductor()));
                                tiquete.setMarca(getString(obj.getMarca()));
                                tiquete.setModelo(getString(obj.getModelo()));
                                tiquete.setLogFirmaVehiculo(getString(obj.getFirmaRepLegal()));
                                tiquete.setAutorizado(getString(obj.getAutorizado()));
                                tiquete.setTipoPago("005");

                                tiquete.setDireccionResponsable(obj.getDireccionResponsable());
                                tiquete.setTelResponsable(obj.getTelResponsable());
                                tiquete.setNombreResponsable(obj.getNombreResponsable());
                                tiquete.setApellidoResponsable(obj.getApellidoResponsable());
                                tiquete.setCcResponsable(obj.getCcResponsable());

                                if (obj.getPersonas() != null) {
                                    int k = 0;
                                    for (Persona persona : obj.getPersonas()) {
                                        if (k == 0) {
                                            tiquete.setCcConductor1((persona.getCcConductor1()));
                                            tiquete.setNombreConductor1(getString(persona.getNombreConductor1()));
                                            tiquete.setApellidoConductor1(getString(persona.getApellidoConductor1()));
                                            tiquete.setLicenciaConductor1(getString(persona.getLicenciaConductor1()));
                                            tiquete.setVigenciaConductor1(getString(persona.getVigenciaConductor1()));
                                        }
                                        if (k == 1) {
                                            tiquete.setCcConductor2((persona.getCcConductor1()));
                                            tiquete.setNombreConductor2(getString(persona.getNombreConductor1()));
                                            tiquete.setApellidoConductor2(getString(persona.getApellidoConductor1()));
                                            tiquete.setLicenciaConductor2(getString(persona.getLicenciaConductor1()));
                                            tiquete.setVigenciaConductor2(getString(persona.getVigenciaConductor1()));
                                        }
                                        if (k == 2) {
                                            tiquete.setCcConductor3((persona.getCcConductor1()));
                                            tiquete.setNombreConductor3(getString(persona.getNombreConductor1()));
                                            tiquete.setApellidoConductor3(getString(persona.getApellidoConductor1()));
                                            tiquete.setLicenciaConductor3(getString(persona.getLicenciaConductor1()));
                                            tiquete.setVigenciaConductor3(getString(persona.getVigenciaConductor1()));
                                        }
                                        i++;
                                    }
                                }

                                /*if (tiquete.getCcConductor1().equals(obj.getCcConductor2())) {//si 
                                 tiquete.setCcConductor2(getString(obj.getCcConductor1()));
                                 tiquete.setNombreConductor2(getString(obj.getNombreConductor1()));
                                 tiquete.setApellidoConductor2(getString(obj.getApellidoConductor1()));
                                 tiquete.setLicenciaConductor2(getString(obj.getLicenciaConductor1()));
                                 tiquete.setVigenciaConductor2(getString(obj.getVigenciaConductor1()));
                                 } else {

                                 tiquete.setCcConductor2(getString(obj.getCcConductor2()));
                                 tiquete.setNombreConductor2(getString(obj.getNombreConductor2()));
                                 tiquete.setApellidoConductor2(getString(obj.getApellidoConductor2()));
                                 tiquete.setLicenciaConductor2(getString(obj.getLicenciaConductor2()));
                                 tiquete.setVigenciaConductor2(getString(obj.getVigenciaConductor2()));
                                 }

                                 tiquete.setCcConductor3(getString(obj.getCcConductor3()));
                                 tiquete.setNombreConductor3(getString(obj.getNombreConductor3()));
                                 tiquete.setApellidoConductor3(getString(obj.getApellidoConductor3()));
                                 tiquete.setLicenciaConductor3(getString(obj.getLicenciaConductor3()));
                                 tiquete.setVigenciaConductor3(getString(obj.getVigenciaConductor3()));*/
                                tiquete.setEmpresa(getString(obj.getEmpresaVehi()));
                                tiquete.setClase(getString(obj.getClase()));
                                tiquete.setNumeroInterno(getString(obj.getNumeroInterno()));
                                tiquete.setNumeroTarjetaOpe(getString(obj.getNumeroTarjetaOpe()));
                                tiquete.setNit(getString(nits));
                                tiquete.setPlaca(obj.getPlaca());

                                srv.setNit(getString(obj.getNitPagador()));
                                srv.setAutoPlaca(PLACA.toUpperCase());
                                srv.setGrabador(user.getUsuario());
                                srv.setValor(tiquete.getValor());

//                                if (tiquete.getNombre() != null) {
//                                    srv.setAddres(tiquete.getDestino() + "|" + tiquete.getNombre() + "|" + tiquete.getNit());
//                                } else {
//                                    srv.setAddres(tiquete.getDestino());
//                                }

                                srv.setFecha(Helper.getColCurrentTime());

                                srv.setUsuarios(tiquete.getUsuario());
                                srv.setTipoPago(tiquete.getTipoPago());
                                srv.setUsuarios(user);
                                srv.setComprob(VJS);
                                srv.setCierre("0");

                                Object[] obj2 = new Object[3];
                                obj2[0] = tiquete;
                                obj2[1] = srv;
                                obj2[2] = entradaPlaca;
                                return obj2;
                            }
                        }

                    }
                    oportunidades++;
                }
            }
            if (oportunidades == 3) {
                new MensajeTmp().createAndShowGui("No se encontraron registros, Favor pruebe con otro vehiculo");
            }

            /*if (nits == null) {
             return null;
             } else {
             // tiquete.setNit("123456789");//HYA QYUE SET DE LA CEDULA DEL PROPIETARIO/CONDUCTGOR ARA HACER LOS PAGOS
             tiquete.setPlaca(PLACA.toUpperCase());

             tiquete.setNitConductor(validaArray(_nits, 9));
             tiquete.setMarca(validaArray(_nits, 4));
             tiquete.setModelo(validaArray(_nits, 3));
             tiquete.setLogEmpreVehiculo(validaArray(_nits, 0));
             tiquete.setLogFirmaVehiculo(validaArray(_nits, 8));
             tiquete.setAutorizado(validaArray(_nits, 0));
             tiquete.setTipoPago("EFECTIVO");
             String nombreConductor = validaArray(_nits, 8);
             tiquete.setNombreConductor1(nombreConductor);
             tiquete.setApellidoConductor1("");
             tiquete.setCcConductor1(validaArray(_nits, 9));
             tiquete.setLicenciaConductor1(validaArray(_nits, 10));
             tiquete.setVigenciaConductor1(validaArray(_nits, 11));
             tiquete.setNombreConductor2(validaArray(_nits, 12));
             tiquete.setApellidoConductor2("");
             tiquete.setCcConductor2(validaArray(_nits, 13));
             tiquete.setLicenciaConductor2(validaArray(_nits, 14));
             tiquete.setVigenciaConductor2(validaArray(_nits, 15));
             tiquete.setNombreResponsable(validaArray(_nits, 16));
             tiquete.setApellidoResponsable("");
             tiquete.setCcResponsable(validaArray(_nits, 17));
             tiquete.setTelResponsable(validaArray(_nits, 18));
             tiquete.setDireccionResponsable(validaArray(_nits, 19));
             tiquete.setEmpresa(validaArray(_nits, 0));
             tiquete.setClase(validaArray(_nits, 5));
             tiquete.setNumeroInterno(validaArray(_nits, 6));
             tiquete.setNumeroTarjetaOpe(validaArray(_nits, 7));
             servicio.setNit(validaArray(_nits, 17));

             tiquete.setNombre(nombre);
             tiquete.setNitCliente(nit);

             servicio.setAutoPlaca(PLACA.toUpperCase());

             servicio.setGrabador(user.getUsuario());
             servicio.setValor(tiquete.getValor());

             if (tiquete.getNombre() != null) {
             servicio.setAddres(tiquete.getDestino() + "|" + tiquete.getNombre() + "|" + tiquete.getNit());
             } else {
             servicio.setAddres(tiquete.getDestino());
             }

             servicio.setFecha(Helper.getColCurrentTime());

             servicio.setUsuarios(tiquete.getUsuario());
             servicio.setTipoPago(tiquete.getTipoPago());
             servicio.setUsuarios(user);
             servicio.setComprob(VJS);
             servicio.setCierre("0");

             Object[] obj = new Object[2];
             obj[0] = tiquete;
             obj[1] = servicio;
             return obj;
             }*/
        } catch (Exception e) {
            e.printStackTrace();
            //  return null;
        }
        //   tiquete = null;

        return null;
    }

    private void dolarPesos() {
        try {
            Integer dolarHoy = new Integer("0");

            Integer cantidadDolar = new Integer("0");

            if (jtfDolarHoy.getText().length() > 7) {
                jtfDolarHoy.setText("0");
            }
            if (jtfCantidadDolar.getText().length() > 5) {
                jtfCantidadDolar.setText("0");
            }

            if (jtfDolarHoy != null && !jtfDolarHoy.getText().isEmpty()) {
                dolarHoy = new Integer(jtfDolarHoy.getText());
            }

            if (jtfCantidadDolar != null && !jtfCantidadDolar.getText().isEmpty()) {
                cantidadDolar = new Integer(jtfCantidadDolar.getText());
            }

            Long lDolarPesos = (long) dolarHoy * cantidadDolar;
            jtfDolarPesos.setText(formateador.format(lDolarPesos));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TiqueteDialog dialog = new TiqueteDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkRetiro;
    private javax.swing.JCheckBox ckPin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jtaDireccion;
    private javax.swing.JTextField jtfCantidadDolar;
    private javax.swing.JTextField jtfCredito;
    private javax.swing.JTextField jtfDarVueltas;
    private javax.swing.JTextField jtfDebito;
    private javax.swing.JTextField jtfDolarHoy;
    private javax.swing.JTextField jtfDolarPesos;
    private javax.swing.JTextField jtfEfectivo;
    private javax.swing.JTextField jtfMainAccount;
    private javax.swing.JTextField jtfValor;
    private javax.swing.JLabel msError;
    private javax.swing.JLabel msjError;
    private javax.swing.JTextField pinPago;
    private javax.swing.JTextField retiro;
    private javax.swing.JTextField saldo;
    private javax.swing.JTextField totalRetiros;
    private javax.swing.JLabel userInformation;
    // End of variables declaration//GEN-END:variables
}
