/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aero.rta.turno;

import com.aero.easypass.tools.PrintPdf;
import com.aero.rta.conn.WebserviceConnection;
import com.aero.rta.dto.JsonDTO;
import com.aero.rta.dto.RtaDTO;
import com.google.gson.Gson;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.util.List;
import java.util.Properties;

/**
 *
 * @author hsancheza
 */
public class PrincipalTurnos extends javax.swing.JFrame {

    String escala;

    public PrincipalTurnos(String escala) {
        this.escala = escala;
        initComponents();
        jButton1.setText("Imprimir " + escala + " turnos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("imprima tiequete.....");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            Toolkit.getDefaultToolkit().beep();

            Properties configFile = readProperties();

            String host = configFile.getProperty("HOST_WS");
            String port = configFile.getProperty("PORT_WS");
            String parqueadero = configFile.getProperty("PARQUEADERO_WS");
            String parqueadero_id = configFile.getProperty("PARQUEADREO_ID_WS");
            String escala = configFile.getProperty("ESCALA");

            String json = "["
                    + "    {"
                    + "        \"empresaId\":\"12\",\n"
                    + "        \"parqueadero\":\"" + parqueadero + "\",\n"
                    + "        \"parqueaderoId\":\"" + parqueadero_id + "\",\n"
                    + "        \"escala\":\"" + escala + "\",\n"
                    + "        \"empresaId\":\"12\",\n"
                    + "	\"keyCommand\":\"17\"\n"
                    + "    }"
                    + "]";

            String jsonIn = new WebserviceConnection(host, new Integer(port)).getStatusAccount(json);
            if (jsonIn != null && !jsonIn.isEmpty()) {
                Gson gson = new Gson();
                RtaDTO obj = gson.fromJson(jsonIn, RtaDTO.class);
                String values = "0";
                for (JsonDTO j : obj.getAlertas()) {
                    values = j.getId().toString();
                    byte[] bytes = new GetTurnosDocs().generarTurno(new Integer(j.getId()), parqueadero);
                    try {
                        PrintPdf printPDFFile = new PrintPdf(bytes, "Test Print PDF");
                        printPDFFile.print();
                    } catch (Exception e) {
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1KeyPressed
    public static String getCurrentWorkingDirectory() {
        String osname = System.getProperty("os.name");
        String userDir = System.getProperty("user.dir");

        if (osname.toLowerCase().contains("windows")) {
            return userDir + "\\";
        } else {
            return userDir + "/";
        }
    }
    public Properties readProperties() {
        Properties configFile = new Properties();
        try {
          String userDir = getCurrentWorkingDirectory();
            String hostFile = userDir + "/" + "host.properties";

            configFile.load(new FileInputStream(hostFile));
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
        return configFile;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalTurnos("Value").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
