/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aero.rta.easypass;

import com.aero.easypass.tools.PrintPdf;
import com.aero.rta.conn.WebserviceConnection;
import com.aero.rta.dto.RtaDTO;
import com.google.gson.Gson;
import com.aero.easypass.tools.Utilitario;
import com.aero.rta.dto.JsonDTO;
import javax.swing.JOptionPane;
import static com.aero.easypass.tools.Utilitario.getInt;
import com.aero.rta.turno.GetTurnosDocs;

import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.Timer;

public class Principal extends javax.swing.JFrame {

    static List<JsonDTO> contratosCache = new ArrayList<JsonDTO>();
    Gson gson = new Gson();
    String host;
    Integer port;
    String codigo = "0";

    public Principal(String host, Integer port) {
        this.host = host;
        this.port = port;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barCode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aero/rta/img/logoCompany.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aero/rta/img/passHand.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        barCode.setBackground(new java.awt.Color(153, 255, 153));
        barCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barCodeActionPerformed(evt);
            }
        });
        barCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barCodeKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 255, 0));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 255, 0));
        jButton2.setText("Admin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo de barras");

        jLabel4.setText("Ingrese numero de contrato");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(barCode, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jButton1))
                    .addComponent(barCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        String value = JOptionPane.showInputDialog("Ingrese Numero de Contrato");
        if (value != null && !value.isEmpty()) {
            String valuesRTA = getStatus(value);
            createAndShowGui(valuesRTA);
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String valuesRTA = getStatus(barCode.getText());

        createAndShowGui(valuesRTA);
    }//GEN-LAST:event_jButton1ActionPerformed

    void createAndShowGui(final String values) {
        final JLabel label = new JLabel();
        int timerDelay = 1000;
        barCode.setText("");
        codigo = "0";
        new Timer(timerDelay, new ActionListener() {
            int timeLeft = 2;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (timeLeft > 0) {
                    label.setText(values + "\nCerrando en... " + timeLeft);
                    timeLeft--;
                } else {
                    ((Timer) e.getSource()).stop();
                    Window win = SwingUtilities.getWindowAncestor(label);
                    win.setVisible(false);
                }
            }
        }) {
            {
                setInitialDelay(0);
            }
        }.start();

        JOptionPane.showMessageDialog(null, label);

    }

    private void barCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barCodeActionPerformed
        // TODO add your handling code here:
        System.out.println("star....");
        String valuesRTA = getStatus(barCode.getText());
        System.out.println("captura: " + valuesRTA);
        createAndShowGui(valuesRTA);
        System.out.println("end..");

        // JOptionPane.showMessageDialog(null, "Vehiculo/Contrato" + getStatus(barCode.getText()));

    }//GEN-LAST:event_barCodeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

//        RequestAdmin frame = new RequestAdmin();
//        frame.setSize(380, 420);
//        frame.setVisible(true);
//        this.setVisible(false);
        new Utilitario().position(new RequestAdmin(host, port));
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void barCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barCodeKeyReleased
        // TODO add your handling code here:
        System.out.println("entrada: " + barCode.getText());
        if (codigo.equals("0")) {
            System.out.println("inicio....");
            //waitLectura("");
            prueba process = new prueba();
            process.execute();
        } else {
            System.out.println("no hacer nada..." + codigo);
        }
        codigo += barCode.getText();

        System.out.println("codigo: " + codigo);
    }//GEN-LAST:event_barCodeKeyReleased

    class prueba extends SwingWorker {

        @Override
        protected Object doInBackground() {
            try {
                System.out.println("inicio tarea...");
                Thread.sleep(1000);
                String valuesRTA = getStatus(barCode.getText());

                createAndShowGui(valuesRTA);
                barCode.setText("0");

            } catch (Exception e) {
            }

            return 0;
        }

        @Override
        protected void done() {

        }
    }

    public static void main(String[] args) {
        String estado = "no";
        try {

            URL ruta = new URL("http://www.google.es");
            URLConnection rutaC = ruta.openConnection();
            rutaC.connect();
            estado = "activo";
        } catch (Exception e) {
            estado = "desactivado";
        }
        System.out.println("internet: " + estado);

        String placa = "273WiW123";
        if (placa.matches("[0-9]*")) {
            System.out.println("solo numeros...");
        } else {
            System.out.println("conbinador " + placa.toUpperCase());
        }
        System.out.println("lena:   " + placa.length());
    }

    public String getStatus(String contrato) {
        String json = "["
                + "    {"
                + "        \"empresaId\":\"12\",\n"
                + "	\"contrato\":\"" + contrato + "\",\n"
                + "	\"fecha\":\"" + Utilitario.getColCurrentTime() + "\",\n"
                + "	\"keyCommand\":\"1\"\n"
                + "    }"
                + "]";

        String JSON_IN = "";

        if (Utilitario.hayInternet2()) {
            JSON_IN = new WebserviceConnection(host, port).getStatusAccount(json);

        } else {
            JSON_IN = new Utilitario().loadFileJson(contrato);
            //JSON_IN = new WebserviceConnection(host, port).getStatusAccount(json);
        }

        System.out.println("RTA: " + JSON_IN);
        RtaDTO rtaDTO = gson.fromJson(JSON_IN, RtaDTO.class);

        if (rtaDTO != null) {

        }
        String mensaje = "Siga... ";
        boolean continuar = true;
        JsonDTO objNuevo2 = null;
        if (rtaDTO != null && rtaDTO.getAlertas() != null) {
            if (rtaDTO.getError().equals("ok")) {
                for (JsonDTO objNuevo : rtaDTO.getAlertas()) {
                    objNuevo.setUltimaImpresion(new Date());
                    long minutos = 0l;
                    if (contratosCache.size() > 0) {
                        for (JsonDTO objAnterios : contratosCache) {
                            objNuevo2 = objNuevo;
                            System.out.println("srv: " + objAnterios.getContrato() + "   " + objNuevo.getContrato() + " " + objNuevo.getBloqueo() + " " + objNuevo.getBloqueoX());
                            if (objAnterios.getContrato().equals(objNuevo.getContrato())) {
                                long[] values = new Utilitario().calcularDiferenciaEntreFechas(objAnterios.getUltimaImpresion(), objNuevo.getUltimaImpresion());
                                minutos = values[2];
                                if (minutos < 15) {
                                    System.out.println("se creo hace poco");
                                    continuar = false;
                                    mensaje = "No!, repitiendo turno";
                                }
                            }
                            long[] todos = new Utilitario().calcularDiferenciaEntreFechas(objAnterios.getUltimaImpresion(), new Date());
                            long minutosTodos = todos[2];
                            if (minutosTodos > 30) {
                                contratosCache.remove(objAnterios);
                            }
                        }
                    }

                    if (continuar) {
                        if (objNuevo.getImprimeTiquete() != null && new Boolean(objNuevo.getImprimeTiquete())) {
                            contratosCache.add(objNuevo);
                            try {
                                byte[] bytes = null;
                                if (getInt(objNuevo.getDias()) > 60) {
                                    mensaje = " CONTRATO[" + objNuevo.getContrato() + "] BLOQUEADO POR MORA";
                                    //sound = audio.getAudio("Bloqueado por pago, " + ob.getDias() + " dias", Language.SPANISH);
                                    bytes = new GetTurnosDocs().generarSalida(
                                            new Integer(objNuevo.getContrato()),
                                            objNuevo.getPlaca(), 
                                            objNuevo.getMsjError(), 
                                            objNuevo.getBloqueo(),
                                            objNuevo.getBloqueoX());
                                } else {
                                    //sound = audio.getAudio("Gracias", Language.SPANISH);
                                    bytes = new GetTurnosDocs().generarSalida(
                                            new Integer(objNuevo.getContrato()), 
                                            objNuevo.getPlaca(), "", 
                                            objNuevo.getMsjError(),
                                            objNuevo.getBloqueoX());
                                }
                                try {
                                    PrintPdf printPDFFile = new PrintPdf(bytes, "Test Print PDF");
                                    printPDFFile.print();

                                    new Utilitario().escribirRegistro(objNuevo.getPlaca(), objNuevo.getContrato(), new Utilitario().toDateYYMMDDHHMM(new Date()));
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                                //  audio.play(sound);
                            } catch (Exception ex) {
                                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }else{
                            mensaje = objNuevo.getMsjError();
                        }
                    }
                }

                System.out.println("MENSAJE: " + mensaje);
                return mensaje;
            } else if (rtaDTO.getError().equals("403")) {
                return "Operacion no permitida por el servidor";
            } else {
                return "Numero de Contrato no encontrado";
            }

        } else {
            return "Verifique la conexion con el servidor";
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
